- Jenkinsfile
- package-lock.json
- package.json
- test/integration/http/aens.js
- test/integration/http/contracts.js
- test/integration/http/oracles.js
- test/integration/http/transactions.js
- test/utils.js
Fixes aeternity/aepp-sdk-docs#15
> Charge test wallets by transferring from pre-provided wallet

- dist/providers/http/index.js
- lib/providers/http/index.js
Add internal URLs back (with dist files)
> Add internal URLs back

- dist/providers/http/services/accounts.js
- dist/providers/http/services/oracles.js
- dist/providers/http/services/transactions.js
- lib/providers/http/services/transactions.js
- package-lock.json
Solve _blocking_ Front-End related problems like:
> Remove nodejs specific code

- CHANGELOG.md
- package.json
Also capitalized project description to stay in line with upstream.
> Add standardized change log with current changes from last tag

- assets/swagger/927f0e7cc2046d367e725422d542f82936fdb1db.json
- package.json
- src/client/contract.js
- src/client/index.js
small fixes to get the compiled version running
> fix linter errors, fix main module path, add specific swagger.json

- src/utils/crypto.js
> Import sha256 directly from "sha.js"

- .babelrc
- package.json
- yarn.lock
> Reduce bundle size by "babel-plugin-ramda"

- Dockerfile.ci
- Jenkinsfile
Change docker node version to 10.12.0
Change `Jenkinsfile` to use `pnpm` instead of `npm`
> Fix docker node version

- docs/bin/commands/chain.md
- docs/bin/commands/inspect.md
- docs/bin/utils/print.md
- shrinkwrap.yaml
Sorry @nduchak apparently something has been lost in the process 😊
> Forgotten files

- es/utils/swagger.js
- test/integration/epoch.js
I've realised that this was an error, when _not_ transpiling `const` in a project.
> Fix assign-to-const error

- es/tx/js.js
- es/tx/tx.js
- es/utils/bignumber.js
- es/utils/bytes.js
- package-lock.json
- package.json
- test/integration/transaction.js
- webpack.config.js
Implement AENS native transaction
Change bignumber libary
> Implement AENS native transaction

- package-lock.json
- package.json
> Use `prepare` lifecycle event instead of `postinstall-build` package

- examples/connect-two-ae/aepp/src/components/Home.vue
required for https://github.com/aeternity/aepp-base/pull/303
>  aepp example: Don't pass click event as options to deploy

- es/ae/contract.js
- es/contract/epoch.js
- es/tx/builder.js
- test/integration/txVerification.js
Use dry-run API for contract static call's
> Use dry-run API for contract static call's

- es/chain/epoch.js
- test/integration/txVerification.js
https://github.com/aeternity/aepp-sdk-js/pull/187#discussion_r243647900
> Disable balance formatting by default

- es/chain/node.js
- es/tx/tx.js
Fix contractCreate fee calculation
> Refactor error handling in sendTransaction

- CHANGELOG.md
- es/ae/contract.js
- es/chain/node.js
- es/channel/handlers.js
- es/channel/index.js
- es/rpc/server.js
- es/tx/builder/index.js
- es/tx/builder/schema.js
- es/tx/tx.js
- es/utils/crypto.js
- package-lock.json
- package.json
- test/integration/channel.js
- test/integration/index.js
- test/integration/transaction.js
- Add `channel` `withdraw` and `deposit` methods
- Change default `gasPrice` in `Contract` stamp and `Tx` stamp to `1e9`
- Fix `contract` tx `fee` calculation
- Refactor error handling in `sendTransaction` function
- Change default `gasPrice` to `1e9`
- Change `Fee` byte_size to 1
- none
- none
- none
> Release 2.3.0-next

- package-lock.json
- test/integration/channel.js
- test/integration/contract.js
From this PR, to have the tests work locally:
1. Set `export WS_URL=ws://localhost:3014` in your local `.env` file
2. Open the necessary port on your local docker-compose override file:
```
version: "3"
services:
node:
ports:
- 3013:3013
- 3113:3113
- 3014:3014
- 3001:3001
```
> Fix channels local tests

- README.md
- package.json
Install comitizen. Configure adapter
Use commitzen to make commits #295
> feat(comitizen): Integrate comitizen for project

- docs/api/chain.md
- docs/api/contract/aci.md
- es/chain/index.js
- es/chain/node.js
- es/contract/compiler.js
- es/utils/crypto.js
- es/utils/http.js
- test/integration/accounts.js
Add ability to get account/balance on specific block hash/height.
Add test.
Add changeCompilerUrl method to Compiler stamp
#302
> Compiler improvements

- es/channel/index.js
- test/integration/channel.js
> Get contract state support

- es/channel/index.js
- test/integration/channel.js
> State channels call contract static support

- es/channel/index.js
> docs(State Channels): Improve state channels documentation

- es/ae/index.js
- test/integration/accounts.js
feat(AE): Allow to spend % of balance.
> feat(AE): Allow to spend % of balance.

- package-lock.json
- package.json
- webpack.config.js
This PR makes possible to generate bundle report for every built file by `npm run build -- --report`.
Example of report:
> Setup webpack-bundle-analyzer plugin

- package-lock.json
- package.json
To avoid double dependency on BigNumber.
Also, I have sent a PR to the upstream repository: https://github.com/sidorares/json-bigint/pull/31
> Use custom version of json-bigint

- es/contract/aci.js
- package-lock.json
- package.json
- test/integration/contract.js
- webpack.config.js
> feat(ACI): Implement arguments validation for generic sophia types(list, map, tuple, record)

- es/contract/aci.js
- test/integration/contract.js
We treat option type as js Promise. Implemented validation and converting option argument. Cover by
test.
> feat(ACI): Add `Option` sophia type to ACI

- .env
- docker/aeternity_node_mean16.yaml
- es/node.js
- es/tx/builder/index.js
- es/tx/builder/schema.js
- es/tx/tx.js
- test/integration/accounts.js
- test/integration/channel.js
Get vm/abi  for contract and oracle transactions based on node protocol
> feat(Consensus): Add function to get consensus version. 

- CHANGELOG.md
- package-lock.json
- package.json
* **Deps:** Update axios lib to 0.19.0 due to security issue ([f951765](https://github.com/aeternity/aepp-sdk-js/commit/f951765))
> Release 3.4.1

- .env
- es/node.js
- test/integration/contract.js
Point node to 3.1.0
Add 4.0.0node compatibility
> chore(Test): Add test for namespaces

- es/node.js
- es/utils/swagger.js
Hello @davidyuk , is it necessary? And why you need that?
>  Make Swagger a sync stamp

- es/account/memory.js
- es/account/selector.js
- es/utils/crypto.js
- es/utils/keystore.js
- es/utils/string.js
- test/unit/memory-account.js
> feat(MemoryAccount): Add validation of keypair

- es/channel/index.js
As per https://github.com/aeternity/aeternity/pull/2576.
> feat(state channels): send generic messages immediately

- es/utils/crypto.js
- test/unit/crypto.js
fixes: https://github.com/aeternity/aepp-sdk-js/issues/606
> Keypair verification

- docs/guides/import-vuejs.md
Should it not be install instead of add?
> install instead of add

- examples/README.md
https://github.com/aeternity/aepp-sdk-js/blob/develop/examples/browser/connect-two-ae needs to be fixed but i don't know the right link.
> Link broken

- es/contract/aci/transformation.js
- test/integration/contract.js
Change Option type Representation from Promise to Value(Some) and undefined(None)
BREAKING CHANGE: Change Sophia option type representation in ACI
> refactor(aci): rework Sophia Option type representation

- .env
- es/ae/aens.js
- es/tx/builder/helpers.js
- es/tx/builder/schema.js
- test/integration/aens.js
Point docker to the rc-5 node and 4.0.0 compiler
Move `classify` method from AENS to transaction builder helpers
> fix(AENS): Change tld for Lima from `aet` to `chain`

- es/tx/builder/helpers.js
- test/integration/aens.js
commitment Id has been generated incorrectly because names have not been transformed to a lower case
> fix(aens): added lower case transformation for aens names

- es/chain/index.js
- es/chain/node.js
- es/contract/aci/index.js
- test/integration/contract.js
Add validation for `contractAddress` and provided bytecode with corresponding one on-chain
> feat(ACI): Add validation for contractAddress

- docs/guides/low-vs-high-usage.md
> Updated link to API

- es/ae/contract.js
- es/contract/aci/index.js
- test/integration/contract.js
> fix(Contract/Chain): Using { waitMined: false } with Contract high lvl API

- docs/api/ae/aens.md
- es/ae/aens.js
- es/tx/builder/helpers.js
- test/integration/aens.js
aensUpdate now accept array of pointers
BREAKING CHANGE: Change aensUpdate method arguments
#865
> feat(aens): implement aensExtendTtl function. Refactor aensUpdate

- es/utils/aepp-wallet-communication/connection/browser-runtime.js
- es/utils/aepp-wallet-communication/rpc/aepp-rpc.js
- es/utils/aepp-wallet-communication/rpc/rpc-clients.js
- es/utils/aepp-wallet-communication/rpc/wallet-rpc.js
- examples/browser/extension/src/js/background.js
- examples/browser/vuejs/connect-two-ae/aepp/package.json
- examples/browser/vuejs/connect-two-ae/aepp/src/components/Home.vue
> feat(AEX-2): Improve disconnect detection for extension communication

- es/utils/aepp-wallet-communication/connection/browser-window-message.js
- es/utils/aepp-wallet-communication/helpers.js
- es/utils/aepp-wallet-communication/rpc/wallet-rpc.js
- examples/browser/extension/package-lock.json
- examples/browser/extension/package.json
- examples/browser/vuejs/connect-two-ae/aepp/package-lock.json
- examples/browser/vuejs/connect-two-ae/identity/package-lock.json
- examples/browser/vuejs/connect-two-ae/identity/package.json
- examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue
> Pass aepp origin to wallet callbacks

- es/utils/aepp-wallet-communication/connection/browser-runtime.js
- es/utils/aepp-wallet-communication/helpers.js
- es/utils/aepp-wallet-communication/rpc/aepp-rpc.js
- es/utils/aepp-wallet-communication/rpc/wallet-rpc.js
- examples/browser/vuejs/connect-two-ae/aepp/src/components/Home.vue
- examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue
Update networkId of Wallet client for each request
> chore(AEX-2): Check for networkId on every signTransaction message

- CHANGELOG.md
- es/utils/aepp-wallet-communication/connection/browser-runtime.js
- es/utils/aepp-wallet-communication/helpers.js
- package-lock.json
- package.json
* **AEX-2:** Fix `isExtensionContext ` check ([#1011](https://github.com/aeternity/aepp-sdk-js/issues/1011)) ([814f99b](https://github.com/aeternity/aepp-sdk-js/commit/814f99b))
> Release 7.4.1

- es/ae/contract.js
- es/contract/aci/index.js
- es/tx/builder/schema.js
- es/utils/aepp-wallet-communication/wallet-detector.js
- test/integration/aens.js
- Resolve contract address from AENS name using Contract/ACI API
- Simplify usage of Wallet detector(make `connection` argument optional)
> Feat(Contract/ACI): Call contract using AENS name

- es/ae/contract.js
- es/ae/index.js
- es/chain/index.js
- es/chain/node.js
- es/contract/aci/index.js
- es/tx/builder/helpers.js
- es/tx/builder/schema.js
- test/integration/aens.js
Implement one generic method for name resolution
> refactor(AENS): Remove duplicated `resolveName`

- examples/browser/vuejs/connect-two-ae/aepp/src/components/Home.vue
- examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue
@CedrikNikita have I missed something?
> example: Add disconnect button on wallet side

- CHANGELOG.md
- es/utils/aepp-wallet-communication/wallet-detector.js
- package-lock.json
- package.json
To fix connection of wallet in iframe to aepp in another iframe
I'm sure that usual and reverse iframe works in the simplest case.
> Release 7.6.0: Use message source in all cases

- es/utils/aepp-wallet-communication/rpc/aepp-rpc.js
- test/integration/rpc.js
Fixed wording in error messages in RPC connection.
> Updated error messages

- es/chain/node.js
- test/integration/chain.js
Inspired by the governance aepp
PR on top of #1072
> Height query optimisation

- es/chain/node.js
> Refactor height query

- es/utils/crypto.js
> assertedType: Make the last parameter more obvious

- README.md
- docs/README.md
- docs/contrib/README.md
- docs/guides/how-to-build-an-wallet-app-or-extension.md
- docs/guides/import-nodejs.md
- docs/guides/import-script-tag.md
- docs/guides/import-tree-shaking.md
- docs/guides/import-vuejs.md
https://sdk-testnet.aepps.com looks a bit outdated, should we switch to https://testnet.aeternity.io?
> Update testnet URL

- es/ae/wallet.js
- es/chain/node.js
- es/node.js
- es/tx/tx.js
- es/tx/validator.js
- examples/browser/extension/src/js/background.js
- examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue
missed in #1083 
Looks like I have accidentally limited the search of `sdk-testnet.aepps.com` to MD files.
> Update testnet URL in JS files

- .gitignore
- docs/guides/import-nodejs.md
...so people know what is necessary.
> nodeJS doc: break down json obj keys necessary for account initialization

- docker/aeternity_node_mean16.yaml
- test/integration/chain.js
- test/integration/contract.js
- test/integration/index.js
Proposing to revert the latest test config updates until the https://github.com/aeternity/aeternity/issues/3516 is fixed.
> Fix integration tests

- docs/guides/contract-events.md
- es/ae/contract.js
- es/chain/index.js
- es/chain/node.js
- es/contract/aci/index.js
- es/utils/swagger.js
> Expose tx events in dry-run call

- es/ae/contract.js
- test/integration/contract.js
> Improve handling of call error

- src/ae/contract.js
- src/contract/aci/index.js
- src/index.js
- src/node-pool/index.js
- src/tx/builder/schema.js
- src/utils/aepp-wallet-communication/wallet-detector.js
- test/integration/contract.js
> Refactor options and related stuff

- src/ae/wallet.js
- src/utils/aepp-wallet-communication/connection/browser-window-message.js
- src/utils/aepp-wallet-communication/helpers.js
- src/utils/aepp-wallet-communication/rpc/aepp-rpc.js
- src/utils/aepp-wallet-communication/rpc/rpc-client.js
- src/utils/aepp-wallet-communication/rpc/rpc-clients.js
- src/utils/aepp-wallet-communication/rpc/wallet-rpc.js
- src/utils/aepp-wallet-communication/wallet-detector.js
- test/integration/rpc.js
Breaking changes:
- removed extra internal structures like `RpcClients` and actions in `RpcClient`
> Refactor new RPC

- src/ae/contract.js
- test/integration/contract.js
> fix: contract error decoding

- src/ae/oracle.js
- src/chain/node.js
- src/contract/ga/index.js
- src/node-pool/index.js
- src/node.js
- src/tx/builder/schema.js
- src/tx/tx.js
- src/utils/aepp-wallet-communication/connection/browser-runtime.js
- src/utils/aepp-wallet-communication/connection/browser-window-message.js
- src/utils/aepp-wallet-communication/connection/index.js
- src/utils/aepp-wallet-communication/content-script-bridge.js
- src/utils/other.js
- src/utils/swagger.js
- test/integration/channel.js
- test/integration/ga.js
- test/integration/index.js
- test/integration/node.js
- test/integration/oracle.js
- test/integration/rpc.js
- test/unit/other.js
closes #1160 
tested with Iris in https://github.com/aeternity/aepp-sdk-js/pull/1163
> Base compatibility with Iris node release

- src/contract/aci/helpers.js
- src/contract/aci/index.js
- src/contract/aci/transformation.js
- src/contract/compiler.js
- src/utils/other.js
- src/utils/swagger.js
- test/unit/other.js
partially reverts 0d821614e83623f5aeb04133197e8c16de7818b1
> fix: revert conversion of case in calls to compiler

- src/chain/index.js
use getNodeInfo from NodePool instead
> docs: remove outdated getInfo docs

- src/utils/swagger.js
> fix: swagger file of aeternity's compiler

- src/account/base.js
- src/ae/index.js
- src/chain/index.js
- src/contract/aci/index.js
- src/contract/ga/helpers.js
- src/contract/ga/index.js
- src/tx/builder/index.js
- src/tx/builder/schema.js
- src/tx/tx.js
- src/tx/validator.js
- test/integration/ga.js
- test/integration/index.js
- test/integration/paying-for.js
fixes #777
depends on #1239
raised issues: https://github.com/aeternity/protocol/issues/490, https://github.com/aeternity/protocol/issues/492
> Support PayingFor transactions

- src/tx/builder/helpers.js
- src/tx/builder/schema.js
- test/unit/tx.js
> Fix name length minimum bid fee

- package.json
> fix: commitlint issue

- test/integration/accounts.js
- test/integration/aens.js
- test/integration/chain.js
- test/integration/contract.js
- test/integration/ga.js
- test/integration/node.js
- test/integration/oracle.js
- test/integration/transaction.js
- test/integration/txVerification.js
In different files we have tests of the same SDK's configuration, naming it differently in different files is confusing to me.
> test: name sdk instance consistent

- src/contract/compiler.js
- src/node.js
- src/utils/swagger.js
- test/integration/contract.js
- test/integration/node.js
closes #1297
Issues reported while doing this:
https://github.com/aeternity/aesophia_http/issues/80
https://github.com/aeternity/aesophia_http/issues/79
https://github.com/aeternity/aesophia_http/issues/78
> Fix error messages

- docs/guides/aens.md
- docs/guides/contract-events.md
- docs/guides/contracts.md
- docs/guides/low-vs-high-usage.md
- docs/guides/oracles.md
- docs/guides/paying-for-tx.md
- examples/node/paying-for-tx-contract-call-tx.js
- mkdocs.yml
when tackling #1323 I found some issues in the docs and fixed those.
> docs: fix navigation and update links to other docs

- apidoc.js
- docs/guides/contracts.md
- examples/node/contract-interaction.js
- examples/node/paying-for-tx-contract-call-tx.js
- src/account/multiple.js
- src/ae/aens.js
- src/ae/contract.js
- src/ae/index.js
- src/ae/oracle.js
- src/chain/node.js
- src/channel/index.js
- src/contract/aci/index.js
- src/contract/ga/index.js
- src/tx/tx.js
- src/utils/aepp-wallet-communication/rpc/aepp-rpc.js
- src/utils/aepp-wallet-communication/schema.js
- test/integration/aens.js
- test/integration/contract-aci.js
- test/integration/contract.js
- test/integration/index.js
- test/integration/node.js
- test/integration/oracle.js
- test/integration/paying-for.js
closes #1322 closes #1321 related to #1291
> feat(aci)!: don't require source code

- docs/guides/contracts.md
- test/integration/contract-aci.js
> Update contract docs

- test/integration/contract-aci.js
> test(contract aci): cover Chain.ttl

- docs/guides/aens.md
- src/ae/aens.js
- src/ae/index.js
- src/chain/node.js
- src/contract/aci/index.js
- src/index.js
- src/tx/builder/helpers.js
- src/tx/builder/schema.js
- test/integration/aens.js
- test/unit/tx.js
> feature(aens)!: don't limit pointer keys

- src/ae/aens.js
- src/ae/index.js
- src/chain/node.js
- src/channel/handlers.js
- src/channel/internal.js
- src/contract/aci/index.js
- src/node-pool/index.js
- src/tx/builder/helpers.js
- src/tx/builder/index.js
- src/tx/tx-object.js
- src/tx/tx.js
- src/tx/validator.js
- src/utils/error.ts
- test/integration/accounts.js
- test/integration/channel.js
- test/integration/node.js
- test/unit/tx-object.js
- test/unit/tx.js
Fix #1194 
source branch: channel and tx errors
target branch: Overall SDK error classes. Current has an open PR against develop branch https://github.com/aeternity/aepp-sdk-js/pull/1345
> Introduce error class in Channel and TX source-code files

- package.json
- test/integration/contract-aci.js
- test/integration/contract.js
> test(contract-aci): ensure that accepts BigNumber

- package.json
- src/tx/builder/index.js
- src/tx/builder/schema.js
- test/integration/aens.js
depends on #1362 
closes #1358
> fix(tx builder): reject more than 32 pointers

- package.json
- test/integration/contract-aci.js
> test(contract-aci): ensure that can get gas and amount

- docs/guides/contract-events.md
- src/chain/node.js
- src/contract/aci/index.js
- src/contract/compiler.js
- src/utils/swagger.js
- test/integration/channel.js
- test/integration/contract-aci.js
- test/integration/transaction.js
> refactor: deprecate tx and getTxInfo methods

- docs/guides/batch-requests.md
- mkdocs.yml
- src/chain/node.js
- src/contract/aci/index.js
- src/utils/swagger.js
- test/integration/chain.js
- test/integration/contract-aci.js
depends on #1362 
closes #963
reported issue https://github.com/aeternity/aeternity/issues/3803
> Making a sequence of requests in efficient way

- package.json
- src/ae/oracle.js
- test/integration/oracle.js
> Refactor oracle

- docs/transaction-options.md
- src/ae/contract.js
- src/contract/aci.js
- src/contract/ga/index.js
- src/tx/builder/schema.js
- test/integration/contract-aci.js
- test/integration/contract.js
- test/integration/transaction.js
closes https://github.com/aeternity/aepp-sdk-js/issues/1286
closes https://github.com/aeternity/aepp-sdk-js/issues/1309
closes https://github.com/aeternity/aeternity/issues/3775
> feat(aci): use dry-run to estimate gas and get rich errors

- docs/guides/contracts.md
- examples/node/contract-interaction.js
- src/ae/contract.js
- src/chain/index.js
- src/chain/node.js
- src/contract/aci.js
- src/contract/ga/index.js
- test/integration/aens.js
- test/integration/chain.js
- test/integration/contract-aci.js
- test/integration/contract.js
- test/unit/crypto.js
depends on #1362
depends on #1363
> Remove deprecated contract methods

- apidoc.js
- package-lock.json
- package.json
- src/tx/builder/helpers.js
- src/utils/async-init.js
- tooling/docs/rtype.js
closes #1291 
Had issues importing it from mjs files.
> refactor: drop ramda package

- src/account/memory.js
- src/ae/universal.js
- src/ae/wallet.js
- src/contract/ga/index.js
- src/index.js
- src/tx/builder/schema.js
- test/integration/ga.js
> fix!: spelling of GeneralizedAccount

- docs/guides/batch-requests.md
- src/chain/node.js
- test/integration/chain.js
- test/integration/contract-aci.js
> fix(dry-run): don't combine requests by default

- src/tx/validator.js
- test/integration/txVerification.js
found issues: https://github.com/aeternity/aeternity/pull/3854 https://github.com/aeternity/aesophia/issues/369
> feat(validator): check contractId

- src/ae/aens.js
- src/ae/contract.js
- src/contract/aci.js
- src/tx/builder/field-types.js
- src/tx/builder/helpers.js
- src/tx/builder/index.js
- src/tx/builder/schema.js
- src/tx/tx.js
- test/integration/contract.js
- test/integration/transaction.js
> Use class-based fields in TxBuilder

- src/ae/contract.js
- test/integration/contract.js
probably fixes a bug in #1274 
found issue: https://github.com/aeternity/aepp-sdk-js/issues/1419
> fix(delegate signature): don't encode address depending on onAccount

- .github/workflows/main.yml
DO NOT MERGE! PR is just to fix the commitlint problem
> Release debug commitlint subhod

- .github/workflows/main.yml
created again to verify behavior of Codecov
> build: exclude tasks on master and remove duplicate task

- package-lock.json
- package.json
- src/utils/crypto-ts.ts
also, can we remove https://github.com/aeternity/blakejs?
> chore: switch to upstream version of blakejs

- src/contract/ga/index.js
- test/integration/ga.js
closes 1/2 of https://github.com/aeternity/aepp-sdk-js/issues/1401
> feat(ga): implement buildAuthTxHash function

- .gitignore
- package.json
- test/examples.sh
> test(examples): on prepublish

- docs/guides/connect-aepp-to-wallet.md
Introducing updated instructions for wallet connection.
Now its in nice copy-pasteble form and cleared from unnecessary code.
Maybe I am not familiar with everything so please suggest changes
> refactor: update instructions to wallet connection tutorial

- docs/quick-start.md
As I went through examples and guides when I was learning about Aeternity I found some clutters.
My motivation here is to make developers onboard smoothly and leave no doubts in that process.
Nothing is written in stone, here are my suggestions.
> refactor: update instructions of Quick Start

- docs/contrib/README.md
- docs/guides/low-vs-high-usage.md
- src/ae/contract.js
- src/chain/index.js
- src/chain/node.js
- src/node-pool/index.js
- src/node.js
- src/tx/tx.js
- src/utils/errors.ts
- src/utils/swagger.js
- test/integration/chain.js
- test/integration/channel.js
- test/integration/index.js
- test/integration/node.js
- test/integration/rpc.js
- test/integration/transaction.js
> refactor(node)!: drop `internalUrl`

- package-lock.json
- package.json
- src/utils/json-big.js
- src/utils/json-big.ts
- test/integration/channel.js
closes #1491 
This PR migrates the `json-big.js` util to TS.
> refactor(utils): migrate json-big.js to TS

- .github/workflows/main.yml
https://github.com/actions/cache#v3
> ci: cache autorest installed packages

- babel.esm.config.js
- package-lock.json
- package.json
- src/account/base.ts
- src/ae/contract.js
- src/contract/ga/index.js
- src/tx/builder/helpers.js
- src/tx/validator.js
- src/utils/crypto.ts
- src/utils/encoder.ts
- src/utils/hd-wallet.ts
- src/utils/other.ts
- test/integration/rpc.js
- test/unit/hd-wallet.ts
> Fix compatibility with create-react-app@4

- docs/guides/build-wallet.md
- docs/guides/connect-aepp-to-wallet.md
- examples/browser/aepp/src/Connect.vue
Updated wallet connection after consultation with @davidyuk 
Now it should not throw any errors caused by not waiting fo connection.
I tried that example snippet and it works
> Update wallet boilerplate

- docs/contrib/README.md
- src/account/Memory.ts
- src/contract/methods.ts
- test/integration/node.ts
Find and fix any either stamp or universe references.
> chore: remove universe stamp referneces

- examples/browser/wallet-web-extension/src/content-script.js
- src/aepp-wallet-communication/connection/Browser.ts
> Aepp-wallet fixes

- examples/browser/aepp/README.md
- examples/browser/wallet-iframe/README.md
- examples/browser/wallet-web-extension/README.md
> docs(examples): add sdk installation details in browser examples

- package-lock.json
- package.json
- src/typings/@aeternity__argon2-browser/index.d.ts
- src/utils/keystore.ts
closes #1587
closes #1586
depends on https://github.com/aeternity/aepp-calldata-js/pull/147
depends on https://github.com/aeternity/aepp-calldata-js/pull/146
> Fix list decoding in contract call results

- docs/guides/build-wallet.md
- docs/guides/connect-aepp-to-wallet.md
- docs/hooks.py
- mkdocs.yml
> docs: inline examples in guides

- test/integration/channel.ts
https://github.com/aeternity/aepp-sdk-js/issues/1619
> test(channel): get contract address on acknowledger side

- src/tx/validator.ts
- test/integration/ga.ts
to make clear issues like this: https://github.com/aeternity/ga-multisig-contract/pull/22#issuecomment-1199049277
Error was:
> Nonce 0 is already used, valid nonce is 2
In addition to it, SDK will say:
> Generalized account can't be used to generate SignedTx with signatures
> feat: ensure that used correct account type while signing transaction

- docs/guides/low-vs-high-usage.md
> docs: update Low vs High level API

- src/aepp-wallet-communication/rpc/RpcClient.ts
- src/chain.ts
- src/contract/aci.ts
- src/contract/ga.ts
- src/tx/index.ts
- src/tx/validator.ts
- src/utils/other.ts
- test/integration/aens.ts
> fix: don't swallow errors without checking its type and message

- src/AeSdkBase.ts
- test/integration/contract-aci.ts
> fix: sync options between Contract and AeSdkBase

- docs/CHANGELOG.md
- package-lock.json
- package.json
> Release 12.1.2: depend on specific version of @azure/core-client

- docs/compatibility.md
> docs: add link to vite setup

- docs/guides/contracts.md
- examples/browser/aepp/src/Contracts.vue
- examples/node/contract-interaction.mjs
- examples/node/paying-for-contract-call-tx.mjs
- src/account/Base.ts
- src/account/Generalized.ts
- src/contract/aci.ts
- src/contract/ga.ts
- test/environment/browser.html
- test/environment/node.js
- test/environment/node.mjs
- test/environment/node.ts
- test/integration/aens.ts
- test/integration/chain.ts
- test/integration/channel.ts
- test/integration/contract-aci.ts
- test/integration/contract.ts
- test/integration/ga.ts
- test/integration/paying-for.ts
- test/integration/transaction.ts
> Rename contract options

- docs/CHANGELOG.md
- package-lock.json
- package.json
- src/contract/aci.ts
* **deps:** update calldata to 1.3.0 ([3eacc29](https://github.com/aeternity/aepp-sdk-js/commit/3eacc29da4e2191dbf449ed4847fca508c342102))
> Release 12.1.3: update @aeternity/aepp-calldata to 1.3.0

- docs/guides/error-handling.md
- src/channel/internal.ts
- src/utils/errors.ts
- test/integration/chain.ts
- test/integration/channel.ts
> fix(channel): emit incoming message handler error instead of printing

- examples/browser/aepp/src/Basic.vue
- examples/browser/wallet-iframe/src/App.vue
- examples/browser/wallet-web-extension/src/background.js
- src/AeSdkWallet.ts
- src/account/Base.ts
- test/integration/rpc.ts
related to aepp-wallet connection refactoring https://github.com/aeternity/aepp-sdk-js/issues/1293#issuecomment-1257810082
> refactor(wallet)!: remove onSign, onMessageSign callbacks

- src/channel/internal.ts
> fix(channel): increase pong timeout 3 times (to 15 seconds)

- docs/guides/oracles.md
- docs/transaction-options.md
- test/integration/oracle.ts
> Update oracle TTL docs

- docs/guides/aens.md
- docs/guides/contract-events.md
- docs/guides/contracts.md
- docs/guides/low-vs-high-usage.md
- docs/guides/oracles.md
- docs/guides/paying-for-tx.md
> Fix inner tx docs

- src/oracle.ts
- test/integration/oracle.ts
closes #1697 
https://github.com/aeternity/protocol/blob/master/oracles/oracle_transactions.md
> fix(oracle): import `getHeight` instead of using a missing context

- docs/guides/contracts.md
- docs/quick-start.md
- examples/browser/aepp/src/App.vue
- examples/browser/aepp/src/Basic.vue
- examples/browser/aepp/src/Connect.vue
- examples/browser/aepp/src/Contracts.vue
- examples/browser/aepp/src/StoreAeSdkPlugin.js
- examples/browser/aepp/src/Value.vue
- examples/browser/wallet-iframe/src/App.vue
- examples/browser/wallet-iframe/src/Value.vue
- examples/browser/wallet-web-extension/src/background.js
- examples/node/contract-interaction.mjs
- examples/node/paying-for-contract-call-tx.mjs
- src/AeSdkBase.ts
- src/AeSdkMethods.ts
- src/account/Base.ts
- src/contract/CompilerHttp.ts
- src/contract/Contract.ts
- src/contract/ga.ts
- src/index.ts
- test/environment/browser.html
- test/environment/ledger/main.mjs
- test/environment/node.js
- test/environment/node.mjs
- test/environment/node.ts
- test/integration/compiler.ts
- test/integration/contract.ts
- test/integration/index.ts
- test/integration/paying-for.ts
- test/integration/rpc.ts
related to https://github.com/aeternity/aepp-sdk-js/issues/1681 https://github.com/aeternity/aepp-sdk-js/issues/1693
> Use compiler@7 in examples, make HTTP compiler not preferable

- src/contract/Contract.ts
closes https://github.com/aeternity/aepp-sdk-js/issues/1682
> docs(contract): document `fileSystem` option

- .github/workflows/main.yml
- docker/aeternity_node_mean16.yaml
- package-lock.json
- package.json
- src/tx/builder/constants.ts
- src/tx/builder/field-types/ct-version.ts
- test/integration/chain.ts
- tooling/autorest/compiler.yaml
- tooling/autorest/node.yaml
https://github.com/aeternity/aeternity/releases/tag/v0.0.0-hc5
based on #1483
> feat: support CERES protocol version

- examples/node/transfer-ae.mjs
- src/spend.ts
> docs: add guide how to transfer fraction of funds

- docs/guides/aens.md
- src/AeSdkMethods.ts
- src/contract/Contract.ts
- src/contract/delegation-signature.ts
- test/integration/contract.ts
Was missed in 24699f15896be0984fc8396979148fa97288dab4
closes #1461
> docs(aens): remove usages of removed `createAensDelegationSignature`

- src/contract/compiler/Base.ts
> fix(contract): type of FunctionAci

- package.json
- tooling/autorest/compiler.yaml
- tooling/autorest/node.yaml
> chore: remove useless autorest parameters

- test/integration/contract.ts
found issues https://github.com/aeternity/aesophia/issues/436
> test(contract): convert message to hash on contract side

- src/Node.ts
- src/contract/compiler/Http.ts
- src/utils/autorest.ts
- test/environment/node-unhandled-exception.mjs
- test/examples.sh
> fix(node): don't throw unhandled exception if version check failed

- test/integration/contract-aci.ts
> test(contract): ensure it can be inherited

- src/contract/compiler/Http.ts
- test/integration/contract-aci.ts
closes #1684 
based on https://docs.aeternity.com/aesophia/v7.0.1/sophia_features/#contract-interfaces-and-polymorphism
> test(contract): supports contract interfaces polymorphism

- src/channel/Spend.ts
- src/contract/Contract.ts
- src/tx/builder/field-types/mptree.ts
- src/utils/errors.ts
- test/integration/contract-aci.ts
> feat(contract): extract $getCallResultByTxHash method

- examples/node/account-generalized.mjs
- mkdocs.yml
- package-lock.json
- package.json
- test/environment/ledger/main.mjs
- test/examples.sh
- test/integration/account-generalized.ts
- tooling/fetch-aesophia-cli.mjs
closes #1243 
related issues https://github.com/aeternity/aeternity/issues/4087 https://github.com/aeternity/aeternity/issues/3947
> docs: add examples/node/account-generalized

- src/index-browser.ts
I was trying to not export it to reduce API, but it is so handy
> feat: export Encoded type

- examples/browser/aepp/src/Connect.vue
- examples/browser/aepp/src/StoreAeSdkPlugin.js
> docs(aepp): rewrite StoreAeSdkPlugin initialization in sync

- test/environment/ledger/browser.mjs
> Fix Ledger example in browser

- package-lock.json
- package.json
> chore(deps): update calldata to 1.4.0

- src/account/Generalized.ts
> refactor(account): note that callData can replace sourceCode and args

- .mocharc.js
- src/AeSdkAepp.ts
- src/aepp-wallet-communication/rpc/types.ts
- test/integration/rpc.ts
> feat(aepp): call onNetworkChange after connection

- docs/README.md
- docs/compatibility.md
- examples/browser/aepp/src/Contracts.vue
- examples/browser/aepp/src/store.js
> docs: add hint on non-compatibility with reactivity in vue@3

- src/contract/Contract.ts
- src/contract/compiler/Base.ts
- src/utils/errors.ts
- test/integration/contract-aci.ts
> fix(contract): add missed `sourceCodePath` cases

- src/tx/execution-cost.ts
> docs(tx-builder): add example of `getExecutionCost`

- .github/workflows/main.yml
based on https://github.com/aeternity/superhero-wallet/pull/2013
> ci: run commitlint only on pull_request

- src/utils/amount-formatter.ts
- test/environment/node.ts
- test/integration/account-generalized.ts
- test/integration/aens.ts
- test/integration/chain.ts
- test/integration/channel.ts
- test/integration/compiler.ts
- test/integration/contract-aci.ts
- test/integration/contract.ts
- test/integration/index.ts
- test/integration/oracle.ts
- test/integration/paying-for.ts
- test/integration/rpc.ts
- test/integration/transaction.ts
- test/integration/txVerification.ts
- test/integration/~execution-cost.ts
- test/unit/crypto.ts
- test/unit/hd-wallet.ts
- test/unit/ledger.ts
- test/unit/memory-account.ts
- test/unit/mptree.ts
- test/unit/pretty-numbers.ts
- test/unit/tx.ts
> export of `prefixedAmount` helper, tests fixes

- docs/guides/address-length.md
- docs/guides/paying-for-tx.md
- examples/node/transfer-ae.mjs
- mkdocs.yml
- src/utils/crypto.ts
- test/unit/crypto.ts
based on https://github.com/aeternity/superhero-wallet/pull/355
> Document possible address length

- src/AeSdkMethods.ts
- src/AeSdkWallet.ts
- src/account/Base.ts
- src/aepp-wallet-communication/schema.ts
- src/chain.ts
- src/channel/Base.ts
- src/channel/internal.ts
- src/contract/compiler/Cli.ts
- src/tx/builder/field-types/coin-amount.ts
- src/tx/validator.ts
- src/utils/autorest.ts
- src/utils/errors.ts
- src/utils/other.ts
- test/integration/rpc.ts
- tsconfig.json
> Enable strict mode except for `strictFunctionTypes`

- docs/compatibility.md
- examples/browser/aepp/src/Contracts.vue
- examples/browser/aepp/src/store.js
> docs: fix link to vue@3 compatibility

- examples/browser/aepp/src/App.vue
- examples/browser/aepp/src/PayForTx.vue
- examples/browser/aepp/src/components/GenerateSpendTx.vue
- examples/browser/aepp/src/styles.scss
- src/AeSdkWallet.ts
- src/account/Rpc.ts
- src/aepp-wallet-communication/rpc/types.ts
- src/tx/builder/field-types/entry.ts
- src/tx/validator.ts
- test/integration/rpc.ts
closes #1503
found issues https://github.com/aeternity/aepp-sdk-js/issues/1832
> feat(aepp,wallet): support inner transaction signing

- examples/browser/wallet-iframe/src/App.vue
- examples/browser/wallet-web-extension/src/background.js
- src/AeSdkMethods.ts
- test/integration/AeSdkMethods.ts
> fix: converting proxied options to JSON

- docs/guides/contracts.md
- docs/quick-start.md
- examples/browser/aepp/src/store.js
- examples/browser/wallet-iframe/src/App.vue
- examples/browser/wallet-web-extension/src/background.js
- examples/node/account-generalized.mjs
- examples/node/contract-interaction.mjs
- examples/node/paying-for-contract-call-tx.mjs
- test/environment/browser.html
- test/environment/ledger/main.mjs
- test/environment/node.js
- test/environment/node.mjs
- test/environment/node.ts
> chore: update to non-staging compiler url

- src/tx/builder/index.ts
- test/integration/Middleware.ts
> fix(tx-builder): `buildTx` produces the same type as `unpackTx` accepts

- test/integration/paying-for.ts
- test/integration/rpc.ts
- test/integration/transaction.ts
> test: avoid using `any`

- docs/CHANGELOG.md
- src/contract/Contract.ts
- src/tx/builder/field-types/fee.ts
- src/tx/builder/field-types/gas-price.ts
- src/utils/crypto.ts
> fix: typos in error messages and docs

- examples/browser/aepp/package.json
- examples/browser/aepp/src/Contracts.vue
- examples/browser/aepp/src/DelegationSignature.vue
- examples/browser/aepp/src/PayForTx.vue
- examples/browser/aepp/src/TypedData.vue
- examples/browser/aepp/src/components/FieldAction.vue
- examples/browser/aepp/src/components/GenerateSpendTx.vue
- examples/browser/aepp/src/components/MessageSign.vue
- examples/browser/aepp/src/components/SpendCoins.vue
- examples/browser/wallet-iframe/package.json
- examples/browser/wallet-web-extension/package.json
> docs(aepp): add on-chain call to aepp example

- docs/guides/typed-data.md
- examples/browser/aepp/package.json
- examples/browser/aepp/src/TypedData.vue
- examples/browser/wallet-iframe/package.json
- examples/browser/wallet-iframe/src/App.vue
- examples/browser/wallet-web-extension/package.json
- examples/browser/wallet-web-extension/src/background.js
- package-lock.json
- package.json
- src/deprecated.ts
- src/index-browser.ts
- src/utils/typed-data.ts
- test/integration/typed-data.ts
> Update aepp-calldata to 1.5.1

- src/contract/Contract.ts
- src/deprecated.ts
- test/integration/contract-aci.ts
- test/utils.ts
> fix(contract): use current nonce in static calls

- src/aens.ts
- test/integration/Middleware.ts
> fix(aens): make `extendTtl` argument optional

- test/integration/index.ts
> test: don't wait for 2 blocks before running tests

- docker-compose.yml
- docker/aeternity_node_mean16.yaml
- package-lock.json
- package.json
- src/contract/compiler/Cli.ts
- src/contract/compiler/Cli8.ts
- src/index.ts
- test/integration/compiler.ts
- test/integration/contract-aci.ts
- test/integration/contract.ts
- test/integration/index.ts
- test/integration/node.ts
- test/integration/transaction.ts
- tooling/fetch-aesophia-cli-8.mjs
- tooling/fetch-aesophia-cli.mjs
depends on https://github.com/aeternity/aepp-calldata-js/pull/251
found issues https://github.com/aeternity/aesophia/issues/491 https://github.com/aeternity/aesophia_cli/pull/84
> Basic Ceres compatibility

- docs/guides/typed-data.md
- test/integration/typed-data.ts
> test: use Chain.network_id in typed data

- src/contract/Contract.ts
- src/tx/builder/schema.ts
- src/tx/validator.ts
- test/integration/aens.ts
related issues https://github.com/aeternity/aeternity/issues/3670 https://github.com/aeternity/aeternity/issues/3669
> feat(contract): resolve names on node side in Ceres

- docker-compose.yml
- test/integration/aens.ts
https://github.com/aeternity/aeternity/pull/4201
> test(aens): claim without preclaim in Ceres

- docker-compose.yml
- src/utils/autorest.ts
https://github.com/aeternity/aeternity/blob/v6.9.0/docs/release-notes/RELEASE-NOTES-6.9.0.md
depends on https://github.com/aeternity/aepp-calldata-js/issues/210
> Update node to 6.12.0

- docs/guides/aens.md
- examples/browser/aepp/src/DelegationSignature.vue
- examples/browser/wallet-iframe/src/App.vue
- examples/browser/wallet-web-extension/src/background.js
- src/AeSdkBase.ts
- src/AeSdkWallet.ts
- src/account/Base.ts
- src/account/Generalized.ts
- src/account/Ledger.ts
- src/account/Memory.ts
- src/account/Rpc.ts
- src/aepp-wallet-communication/rpc/types.ts
- test/integration/contract.ts
based on https://github.com/aeternity/aeternity/pull/4105
> Support all names delegation to contract (in Ceres)

- .gitignore
- docker-compose.yml
- docs/guides/aens.md
- examples/browser/aepp/src/DelegationSignature.vue
- examples/browser/wallet-iframe/src/App.vue
- examples/browser/wallet-web-extension/src/background.js
- src/AeSdkBase.ts
- src/AeSdkWallet.ts
- src/account/Base.ts
- src/account/Generalized.ts
- src/account/Ledger.ts
- src/account/Memory.ts
- src/account/Rpc.ts
- src/aepp-wallet-communication/rpc/types.ts
- src/aepp-wallet-communication/schema.ts
- src/contract/delegation-signature.ts
- src/index-browser.ts
- src/tx/builder/common.ts
- src/tx/builder/delegation/index.ts
- src/tx/builder/delegation/schema.ts
- src/tx/builder/index.ts
- test/integration/contract.ts
- test/integration/rpc.ts
- test/unit/delegation.ts
- test/unit/tx.ts
- tooling/generate-schema.ts
> feat: support new delegation format in Ceres

- src/contract/Contract.ts
- test/integration/contract-aci.ts
> fix(contract): don't duplicate NoSuchContractFunctionError message

- docker-compose.yml
- src/contract/compiler/Cli.ts
- src/contract/compiler/Http.ts
- test/integration/compiler.ts
- test/integration/index.ts
- test/integration/transaction.ts
- tooling/fetch-aesophia-cli-8.mjs
- tooling/fetch-aesophia-cli.mjs
> chore: update aesophia to 8.0.0-rc1, enable http compiler in tests

- tooling/autorest/middleware-prepare.mjs
- tooling/downlevel/run.mjs
- tooling/fetch-aesophia-cli-8.mjs
- tooling/fetch-aesophia-cli.mjs
- tooling/restore-file.mjs
> Stop build process if child process exited with non-0 code

- src/channel/Base.ts
- src/channel/internal.ts
- test/integration/channel.ts
- test/integration/compiler.ts
- test/integration/index.ts
- test/integration/node.ts
- test/integration/rpc.ts
- test/integration/~execution-cost.ts
> Refactor tests

- .mocharc.js
- src/utils/autorest.ts
- test/integration/AeSdkMethods.ts
- test/integration/accounts.ts
- test/integration/aens.ts
- test/integration/chain.ts
- test/integration/channel.ts
- test/integration/contract-aci.ts
- test/integration/delegation.ts
- test/integration/index.ts
- test/integration/oracle.ts
- test/integration/rpc.ts
- test/integration/txVerification.ts
- test/integration/~execution-cost.ts
> test: add ability to run on testnet, mainnet

- src/Node.ts
- src/tx/builder/field-types/entry.ts
- src/tx/builder/field-types/fee.ts
- src/tx/validator.ts
- tsconfig.json
> chore: fix docs build

- src/spend.ts
- src/tx/builder/schema.ts
- src/tx/validator.ts
- test/integration/chain.ts
- test/integration/contract-aci.ts
found issue https://github.com/aeternity/aeternity/issues/4310
https://docs.aeternity.com/aesophia/v7.4.1/sophia_features/#payable-contracts
> feat: spend to payable contract

- .github/workflows/main.yml
- src/chain.ts
- src/oracle.ts
- src/tx/builder/field-types/ttl.ts
- test/integration/AeSdk.ts
- test/unit/ae-sdk.ts
Using this branch, I've removed custom intervals in cli tests https://github.com/aeternity/aepp-cli-js/pull/256
> fix: ttl validation error in dev mode by reducing polling intervals

- src/AeSdkWallet.ts
> fix(wallet): origin if opened over file:// (cordova)

- .mocharc.js
- docker-compose.yml
- src/channel/Base.ts
- src/channel/internal.ts
- test/integration/MiddlewareSubscriber.ts
- test/integration/channel.ts
- test/utils.ts
`statePassword` was removed in https://github.com/aeternity/aeternity/pull/2911
found issues https://github.com/aeternity/protocol/pull/529
> Improve channel tests and fixes

- examples/README.md
- examples/node/dry-run-using-debug-endpoint.mjs
- mkdocs.yml
- test/examples.sh
found issues https://github.com/aeternity/aeternity/issues/4369
> docs(node): explain how to use debug dry-run instead protected

- test/integration/contract-aci.ts
based on https://docs.aeternity.com/aesophia/v8.0.1/sophia_features/#contract-factories-and-child-contracts
done while searching for the reproduction of https://github.com/aeternity/aepp-calldata-js/issues/277
> test(contract): ensure `Chain.create`, `Chain.clone` works

- docker-compose.yml
- docker/middleware.yaml
- src/Middleware.ts
- src/index-browser.ts
- test/integration/Middleware.ts
- test/integration/MiddlewareSubscriber.ts
- test/integration/reset-middleware.ts
- tooling/autorest/middleware-prepare.mjs
found issues https://github.com/aeternity/ae_mdw/issues/1841 https://github.com/aeternity/ae_mdw/pull/1840 https://github.com/aeternity/ae_mdw/pull/1844
> Run middleware locally for tests, require v1.81.0

- src/Node.ts
- src/aepp-wallet-communication/rpc/types.ts
- src/chain.ts
- src/contract/Contract.ts
- src/send-transaction.ts
- src/tx/validator.ts
- src/utils/autorest.ts
- test/integration/AeSdkMethods.ts
- test/integration/chain.ts
- test/integration/contract-aci.ts
- test/integration/index.ts
- test/integration/node.ts
- test/integration/transaction.ts
- tooling/autorest/node.yaml
- tooling/autorest/postprocessing.mjs
the same approach as in #2007 
> fix(node): avoid complex types by code replacements instead generics

- docker-compose.yml
- docker/middleware.yaml
- src/Middleware.ts
- src/utils/autorest.ts
- test/integration/Middleware.ts
- test/integration/node.ts
- test/integration/reset-middleware.ts
- tooling/autorest/middleware-openapi-temp.yaml
- tooling/autorest/middleware-prepare.mjs
- tooling/autorest/middleware.yaml
- tooling/autorest/node.yaml
- tooling/autorest/postprocessing.mjs
found issues https://github.com/aeternity/ae_mdw/pull/1849 https://github.com/aeternity/ae_mdw/issues/1850 https://github.com/aeternity/ae_mdw/issues/1852 https://github.com/aeternity/ae_mdw/issues/1853 https://github.com/aeternity/ae_mdw/issues/1854 https://github.com/aeternity/ae_mdw/issues/1855 https://github.com/aeternity/ae_mdw/issues/1856 https://github.com/aeternity/ae_mdw/issues/1857 https://github.com/aeternity/ae_mdw/issues/1858 https://github.com/aeternity/ae_mdw/pull/1859 https://github.com/aeternity/ae_mdw/issues/1860 https://github.com/aeternity/ae_mdw/pull/1868 https://github.com/aeternity/ae_mdw/issues/1872 https://github.com/aeternity/ae_mdw/pull/1873
https://github.com/Azure/azure-sdk-for-js/blob/ea3c2f414b485881b6d54b6e8511 …
> Middleware: switch to v3, accurate coin amounts, fix word casing

- src/Middleware.ts
- src/index-browser.ts
- src/utils/MiddlewarePage.ts
- src/utils/autorest.ts
- test/integration/Middleware.ts
- tooling/autorest/postprocessing.mjs
> feat(middleware): allow navigate to next/prev pages

- test/integration/Middleware.ts
- tooling/autorest/middleware-openapi-temp.yaml
- tooling/autorest/middleware.yaml
- tooling/autorest/postprocessing.mjs
found issues https://github.com/aeternity/ae_mdw/pull/1909
> feat(middleware): prefixed types provided by OpenApi instead of strings

- examples/browser/aepp/src/Connect.vue
- examples/browser/aepp/src/components/SelectNetwork.vue
- examples/browser/wallet-iframe/src/App.vue
- examples/browser/wallet-web-extension/src/background.js
- examples/browser/wallet-web-extension/vue.config.js
- src/AeSdkAepp.ts
- src/AeSdkWallet.ts
- src/aepp-wallet-communication/WalletConnectorFrameBase.ts
- src/aepp-wallet-communication/rpc/types.ts
- src/aepp-wallet-communication/schema.ts
- src/index-browser.ts
- test/integration/rpc.ts
> feat(aepp)!: add api to ask wallet to select network

- docs/README.md
- examples/browser/aepp/src/Basic.vue
- examples/browser/aepp/src/Connect.vue
- examples/browser/aepp/src/components/ConnectLedger.vue
- examples/browser/aepp/src/components/ConnectMetamask.vue
- examples/browser/aepp/src/components/ConnectMnemonic.vue
- src/account/MnemonicFactory.ts
> Add ConnectMnemonic and Discovery Accounts button to aepp example

- src/Middleware.ts
- src/Node.ts
- src/contract/compiler/Cli.ts
- src/contract/compiler/Http.ts
- src/tx/validator.ts
- src/utils/autorest.ts
- test/integration/chain.ts
- test/integration/node.ts
- test/unit/ledger.ts
- test/unit/mnemonic.ts
> feat(node): ignore consensus protocol version if `ignoreVersion` set

- docs/guides/batch-requests.md
> docs(chain): compare spend tx vs spend via contract

- src/contract/Contract.ts
- test/integration/contract-aci.ts
- test/integration/delegation.ts
> fix(contract): type checking of contract call return value

- docs/guides/oracles.md
- src/oracle/Oracle.ts
- src/oracle/OracleBase.ts
- src/oracle/OracleClient.ts
- test/integration/oracle.ts
> feat(oracle): add `getQueries` to OracleBase

- docs/guides/typescript.md
- mkdocs.yml
- tsconfig.json
https://docs.aeternity.com/aesophia/v8.0.1/sophia_stdlib/#string
> docs: add TypeScript guide

- docs/guides/metamask-snap.md
- examples/browser/aepp/src/components/ConnectMetamask.vue
- src/account/Metamask.ts
- src/account/MetamaskFactory.ts
- test/unit/metamask.ts
https://docs.metamask.io/snaps/how-to/connect-to-a-snap/
> Implicitly connect to Aeternity snap, detect MetaMask over EIP-6963

- package-lock.json
- package.json
- src/utils/crypto.ts
- test/unit/crypto.ts
> Drop `varuint-bitcoin`

- src/oracle/Oracle.ts
- src/tx/builder/constants.ts
- src/tx/builder/field-types/fee.ts
- src/tx/builder/schema.ts
- src/tx/execution-cost.ts
- test/integration/transaction.ts
- test/integration/~execution-cost.ts
related issue https://github.com/aeternity/aeternity/issues/2799
> fix(tx-builder): replace OracleResponseTx with OracleRespondTx

- docs/guides/contract-events.md
Just some broken links I found in the SDK docs as I was reading through.
> Update Docs Links for Conract Events

- docs/CHANGELOG.md
- docs/guides/address-length.md
- docs/guides/aens.md
- docs/guides/contract-events.md
- docs/guides/contracts.md
- docs/guides/low-vs-high-usage.md
- docs/guides/migration/14.md
- docs/guides/oracles.md
- docs/guides/paying-for-tx.md
- docs/guides/typescript.md
- examples/node/transfer-ae.js
> docs: fix links to documentation hub, examples and API reference

- LICENSE
- README.md
- package.json
related PR: https://github.com/aeternity/aepp-cli-js/pull/273
> chore: add homepage to package.json

- examples/browser/tools/index.html
- examples/browser/tools/src/app.tsx
- examples/browser/tools/src/components/AccountsByMnemonic.tsx
- examples/browser/tools/src/components/ConvertSk.tsx
- examples/browser/tools/src/components/DataEncoder.tsx
- examples/browser/tools/src/index.css
> docs: add encoding/decoding, generate accounts/mnemonics in sdk tools

- examples/browser/aepp/src/components/ConnectLedger.vue
- src/account/LedgerFactory.ts
- test/unit/ledger.ts
found issues https://github.com/LedgerHQ/ledger-live/issues/9462 https://github.com/aeternity/ledger-app/issues/23
> Experimental support of Ledger app v1.0.0

- README.md
- docs/guides/low-vs-high-usage.md
- docs/guides/typescript.md
> docs: fix links with code blocks in mkdocs
