lib/providers/http/index.js

Add back `/internal`, to be able to test basic functionalities like: _getBalance_

Add internal URLs back

---

.gitignore
src/utils/crypto.js
test/crypto.js

For the Voting app, it is necessary to implement methods for signing and verifying of personal messages. But I can't find anything that describes how this messages should be signed on Aeternity. I propose to use the approach similar to Bitcoin and Ethereum approaches.
In https://github.com/ethereum/go-ethereum/issues/14794 proposed to use `varint` from Bitcoin to store message length, I suppose to implement it later in case if this whole approach is acceptable.
Depends on #32

Add sign and verify for personal messages

---

package.json

Alternatively, we can add `yarn` to dev dependencies 🙂

Don't require Yarn to build the package on "postinstall"

---

test/unit/crypto.js

As I know from https://github.com/aeternity/aepp-identity/pull/147 Epoch address length in between 51 and 53 chars.
Fixes failure of this test: https://ci.aepps.com/blue/organizations/jenkins/aepp-sdk-js/detail/PR-116/3/tests

crypto tests: Set minimum address length to 51

---

es/utils/crypto.js

This fixes the error that I have in the Base app when I'm trying to use aepp-sdk@1.1.2:
```
VM3844 crypto.js:499 Uncaught TypeError: Cannot read property 'decode' of undefined
at Module.eval (VM3844 crypto.js:499)
at eval (VM3844 crypto.js:590)
at Module../node_modules/@aeternity/aepp-sdk/es/utils/crypto.js (VM3699 app.js:1229)
at __webpack_require__ (VM3699 app.js:768)
at fn (VM3699 app.js:131)
at Module.eval (VM3839 index.js:6)
at eval (VM3839 index.js:111)
at Module../node_modules/@aeternity/aepp-sdk/es/account/index.js (VM3699 app.js:917)
at __webpack_require__ (VM3699 app.js:768)
at fn (VM3699 app.js:131)
```

Fix import of RLP package

---

package.json

Use rlp 2.1.0 due to issue with building latest version(require dev-dependency BN.js)

Use rlp 2.1.0 due to issue with building

---

es/rpc/client.js
es/rpc/server.js

Without this I can't put the instance of sdk in Vuex store because of error:
```
vue.runtime.esm.js:1964 Uncaught (in promise) RangeError: Maximum call stack size exceeded
at Function.keys (<anonymous>)
at _traverse (vue.runtime.esm.js:1964)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
at _traverse (vue.runtime.esm.js:1966)
``` …

RpcServer: Avoid storing of window in instance properties

---

CHANGELOG.md
package.json
test/integration/index.js

- `Minerva` comparability
- Add `Mnemonic` wallet implementation `es/utils/hd-wallet`
- Change Channel `legacy` API to `JSON RPC`
- Change default `gasPrice` to `1e6`
- Change `minFee` calculation, multiply min fee by `1e9`
- none
- none
- Change supported node version range to `1.4.0 <= version < 3.0.0`
- This release contain changes from: [2.3.0-next](https://github.com/aeternity/aepp-sdk-js/releases/tag/2.3.0-next), [2.2.1-next](https://github.com/aeternity/aepp-sdk-js/releases/tag/2.2.1-next), [2.1.1-0.1.0-next](https://github.com/aeternity/aepp-sdk-js/releases/tag/2.1.1-0.1.0-next), [2.1.0](https://github.com/aeternity/aepp-sdk-js/releases/tag/2.1.0)

Release 2.3.0

---

es/channel/handlers.js
es/channel/index.js
test/integration/channel.js

Implements #289
Breaking changes:
- `channel.state()` now returns offchain state instead of last co-signed offchain transaction
- `channel.update(...).state` has been renamed to `signedTx`
- `channel.withdraw(...).state` has been renamed to `signedTx`
- `channel.deposit(...).state` has been renamed to `signedTx`
- `channel.leave().state` has been renamed to `signedTx`
- `channel.createContract(...).state` has been renamed to `signedTx`
- `channel.callContract(...).state` has been renamed to `signedTx`

Get full channel state support

---

examples/connect-two-ae/aepp/src/components/Home.vue
examples/connect-two-ae/identity/src/components/Home.vue

The last commit of this PR contains a prototype of 'reverse-iframe' approach that we are going to implement in the desktop version of Base app and make it compatible with hybrid voting aepp.
This implementation doesn't require any changes in SDK, though would be better to integrate them into sdk somehow to make dapps building easier. 
ps: I was too lazy to rebase it on top of develop branch, so it contains changes from #347, I believe what that PR will get merged earlier than this one.

Add prototype of reverse iframe approach to example aepp

---

webpack.config.js

This affects only the built version of sdk, e.g when it used by importing of '@aeternity/aepp-sdk' (without `/es`).
The idea of this PR is to make possible to reuse dependencies of sdk by other packages or the code of a project that depends on SDK. Also, it makes more understandable SDK dependencies and it's actual size. After all, it makes SDK bundle smaller, making the build of SDK faster and disables `WARNING in asset size limit: The following asset(s) exceed the recommended size limit`.
Before:
After:
There reports generated by https://github.com/davidyuk/vue-reproductions/tree/sdk-external-dependencies project, using `npm run build -- --report`
The same configs we have in components repository: https://github.com/aeternity/aepp-components/blob/b891e32030291e1da8042c242a84eb14315d3b8c/ …

webpack configs: Mark all dependencies as external

---

es/rpc/client.js

`window.parent` is equal to `window` if a web page opened as usual. If we accidentally start dapp in this way (also not setting `parent` option), then `rpc/client` will send a `hello` to itself and fail with exception:
> Uncaught TypeError: Cannot destructure property `resolve` of 'undefined' or 'null'. at receive (client.js?aafa:56)
I think much cleaner for dapp developers to handle this case separately. In that case this PR makes dapp to throw:
> Uncaught (in promise) Error: rpc client: Can't send messages to itself at Object._callee$ (client.js?6b57:46)

rpc client: Handle case if aepp opened without wallet

---

es/contract/compiler.js
es/node.js

BREAKING CHANGE: This change will make the release not compatible with older version of the node and compiler

refactor(SCM): Update compatibility range for node: 3.0.1 - 4

---

README.md

The referenced file `docs/usage.md` does not exist.

README: fix flavor link

---

docs/README.md
docs/guides/import-script-tag.md
es/node.js
webpack.config.js

build(webpack): Add another bundle for using in `<script>` tag

---

es/channel/internal.js

Fixes a bug which caused unneccessary params (for example: sign, url) to be included to websocket
url.

fix(State Channels): Fix websocket url

---

es/utils/swagger.js

I'm using Swagger stamp to map [middleware api file](https://github.com/aeternity/aepp-middleware/issues/65) to js interface. It works fine except cases when I need to pass parameters to get method. For example, when I'm calling `.namesReverseGet('ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ', { limit: 1, page: 2 })`, `limit` and `page` params gets omitted by current implementation. This PR fixes it.

swagger: Pass query params in case of get request

---

AUTHORS
CHANGELOG.md
docs/api.md
docs/api/contract/aci.md
docs/api/utils/keystore.md
docs/examples/node/aecontract.md
es/ae/wallet.js
es/chain/index.js
es/contract/aci/index.js
es/utils/keystore.js
package-lock.json
package.json

* **ACI:** Disable bytecode check for source and code on-chain. This changes will be included in next major release ([#783](https://github.com/aeternity/aepp-sdk-js/issues/783)) ([fe6021b](https://github.com/aeternity/aepp-sdk-js/commit/fe6021b))
* **KeyStore:** Remove `argon2` package, use `libsodium` for both browser and node ([#782](https://github.com/aeternity/aepp-sdk-js/issues/782)) ([c18047e](https://github.com/aeternity/aepp-sdk-js/commit/c18047e))

Release 6.1.1

---

es/chain/index.js
es/chain/node.js
test/integration/aens.js
test/integration/chain.js

Add new option `{ confirm: 3 }` to all of `high lvl SDK API`. Add tests. Adjust docs

feat(Chain): add new method `waitFOrTxConfirm`

---

es/account/index.js
es/account/memory.js
es/utils/aepp-wallet-communication/rpc/wallet-rpc.js
test/integration/rpc.js
test/unit/memory-account.js

Extend `verifyMessage` with ability to accept `buffer` or `hex`

feat(AEX-2): Use `hex` string for `signMessage` response

---

es/utils/aepp-wallet-communication/helpers.js
es/utils/aepp-wallet-communication/rpc/rpc-clients.js
test/integration/rpc.js

`messageId` in `RpcClient` is defined as a constant, and it is passed to `sendMessage` and `receive` methods as a primitive value, but as I know primitive variables are passed by values (not by reference) so it can't be mutated outside of function scope, also `messageId` can't be mutated because it is defined as a constant.
So, I propose to drop not working and confusing code.

RpcClient: Simplify message id processing

---

es/utils/keystore.js
test/unit/keystore.js

`KeyStore.dump` accept secret as `hex` or `buffer`

feat(Keystore): Allow to store secret as hex or buffer

---

.travis.yml

This PR partially reverts 51c661dc4ece4235a1fb4dd71b0a28f323e1f668.
The goal is to avoid double-checking of all RPs.
Initially, I wanted to disable the testing of PRs and keep branch testing, but as we checked in https://github.com/aeternity/aepp-sdk-js/pull/1053 disabling of PR builds will complicate test running on third-party PRs.

Disable Travis on all branches except master, develop

---

es/ae/index.js
es/chain/index.js
es/tx/tx.js
es/tx/validator.js
test/integration/accounts.js

transferFunds: Accept onAccount option

---

es/utils/bytes.js
test/unit/bytes.js

Implementing #1060 I have found that passing a non-integer amount value looks working, but actually the amount value is gets broken instead of being rounded somehow. `BigNumber.toString(16)` returns a hex value separated with a dot for non-integer values that get passed to `Buffer.from` that just ignores the part after `.`:
```
> Buffer.from('390cf7311ac9f5ab9746ab.2ab9f559b3d07c84b5dd', 'hex')
<Buffer 39 0c f7 31 1a c9 f5 ab 97 46 ab>
```
Alignment by adding a leading 0 also may not work properly in this case.
`bigNumberToByteArray` is handling non-integers not properly, so I propose to throw an exception then.

bigNumberToByteArray: Avoid unexpected behaviour by throwing exception

---

test/integration/chain.js
test/integration/contract.js
test/integration/index.js

There are more places where the default 5s pooling interval is used - need to find them.
This reduces Tx confirmation times 5 times :)

Speed up some tests 5 times

---

docs/conda.yml

Currently, readthedocs build is broken, because firstly, Conda installs python@3.9.0 and then run readthedocs's scripts:
> conda install --yes --quiet --name latest mock pillow
That depends on python@3.8.5. Reinstalling of python removes the installed packages, so resulting in error:
> ERROR   -  Config value: 'plugins'. Error: The "mkdocs-simple-hooks" plugin is not installed 
Specifying the python@3.8 helps to get rid of the error, but until builtin readthedocs scripts will become dependent on a newer python.
related to #1089 
build log: https://readthedocs.org/projects/aepp-sdk-js/builds/12399787/

Specify the python version more precisely

---

docker/aeternity_node_mean16.yaml
es/chain/node.js
test/integration/chain.js

Now with the polling interval fixed we can increase the mining rate of the node.
Tests now finally execute in reasonable amounts of time :)
How to improve this even further:
1. JS ACI calldata encoder/decoder
2. Instant mining in the node
Will see when I will be in the mood to implement those ;)
PR on top of #1073

Better node defaults

---

src/ae/aens.js
src/chain/node.js
src/tx/builder/helpers.js
src/tx/builder/schema.js
test/integration/transaction.js
test/unit/tx.js

Breaking changes:
- removed `nameHash` from `builder/helpers`
- `isNameValid` won't throw exceptions
- removed `AENS_NAME_DOMAINS` from `builder/schema`
- removed default export of `builder/helpers`
Features:
- added `ensureNameValid` function that will throw exception if name is not valid

Drop old names support, split ensureNameValid and isNameValid

---

src/account/multiple.js
src/ae/universal.js
test/integration/index.js
test/integration/rpc.js

SDK is a library and retrieving the account from the process environment seems to be more suitable for the end-user product like sdk cli or so. Also, it may lead to unexpected behavior if sdk would be used in an app that manages accounts by itself.

refactor: don't retrieve account from process.env

---

src/utils/amount-formatter.ts
src/utils/bignumber.ts
test/unit/amount-formatter.ts

Probably it was necessary before when BigNumber was throwing an exception when passing a number that is not presented precisely.

refactor: use BigNumber constructor instead of custom wrapper

---

src/chain/node.js
src/utils/swagger.js

uses feature implemented in https://github.com/aeternity/aeternity/pull/3628

Deprecate internal API, switch to protectedDryRunTxs

---

src/ae/aens.js
src/tx/builder/schema.js

The validity of domain name renewal after IRIS should be changed to `180000`, currently, it is still `5000`. Restrictions are made in the SDK. I have modified this

Fix lris updating domain name maximum height issue

---

package-lock.json
package.json
webpack.config.js

before:
```
$ ls -lah dist 
2.1M aepp-sdk.browser-script.js
6.6M aepp-sdk.browser-script.js.map
328K aepp-sdk.browser.js
1.1M aepp-sdk.browser.js.map
325K aepp-sdk.js
1.1M aepp-sdk.js.map
```
after this and #1208:
```
$ ls -lah dist
955K aepp-sdk.browser-script.js
3.5M aepp-sdk.browser-script.js.map
327K aepp-sdk.browser.js
1.1M aepp-sdk.browser.js.map
325K aepp-sdk.js
1.1M aepp-sdk.js.map
```
fixes `aepp-sdk.browser-script.js` package, discussed in https://forum.aeternity.com/t/issues-with-sdk8-0-0/9453/8
also should fix this issue: https://github.com/crypto-browserify/pbkdf2/issues/48#issuecomment-842311861 😃

Fix and make smaller browser script

---

src/utils/swagger.js

Added `https` check for the origin URL of the compiler, not only for the hosted compilers.
workaround for https://github.com/aeternity/aesophia_http/issues/70
ref: https://github.com/aeternity/aepp-sdk-js/issues/1225#issuecomment-863985169

fix: swagger https issue

---

package-lock.json
package.json

Since latest webpack versions dropped the default "events" package, during a fresh setup of the SDK manual installation of the "events" package is necessary. Saved it in the `package.json` file

Add events package to package manager file to fix webpack building

---

docs/contrib/README.md

The existing Node.JS version requirement in REAMDE.md under docs/contrib is outdated.
`pnpm install` returns with a message `Node.JS version >= v12.17 required`. Hence updating the document with appropriate Node.js engine version.

Update minimum Node.js version in Contribution README

---

src/ae/contract.js
test/integration/contract.js

Fix #1232 
Solution: In the  `contractDeploy` method, overwrite the `deposit` key in the options.

Enforce zero value of deposit while Contract deployment

---

src/account/multiple.js
test/integration/chain.js
test/integration/index.js
test/integration/transaction.js

Issue descriptions:  #1224 
Process accounts in `accounts stamp` only when it's not empty.
Modify BaseAe SDK setup in integration tests to accomodate accountless instances.
Use Accountless stamp(openClient) in Chain tests.

Fix default account required to setup universal stamp of the SDK issue

---

docs/transaction-options.md
src/tx/builder/schema.js

Issue disucssion: Fix #1267 
Solution: Change default gas from ` 1600000 - 21000` to `25000`.  Discussion on the new value https://github.com/aeternity/aepp-sdk-js/issues/1267#issuecomment-909291108 
Updated the docs to reflect the changes.

Modify default gas to a reasonable number and update docs with Gas estimation

---

src/ae/universal.js
test/integration/channel.js

Fix #1132 
Solution: Import Channel stamp in the Universal stamp and update the `channel tests` with universal stamp instead of direct Channel stamp

Make Channel a part of Universal stamp

---

docs/quick-start.md
examples/README.md
examples/node/contract-interaction.js
examples/node/paying-for-tx-contract-call-tx.js
examples/node/paying-for-tx-spend-tx.js
examples/node/transfer-ae.js

to be consistent we remove the token wording for AE in every place

docs: remove token wording for AE

---

docs/guides/aens.md
src/ae/contract.js
test/integration/contract.js
test/integration/oracle.js

Oracle delegation signature issue: #1242 
Aens delegation signature issue: #1237 
Design & solution: All the AENS and Oracle delegation methods use the common method `delegateSignatureCommon` for signing. The common method used to include the address for signing even if the `onAccount` is not set in the options.  Hence the solution is to modify the common method to use the address for signing only if the `onAccount` key exists in the options.
This will resolve @marc0olo comment https://github.com/aeternity/aepp-sdk-js/issues/1242#issuecomment-918335331 on `delegateOracleRespondSignature`
Further updates on the changes:
* Javascript doesn't support function overloading. The new approach is `Accept params as Object` to merge the common signature delegation methods
* Update AENS & Oracle …

Fix AENS and Oracle delegation signature

---

src/ae/universal.js
test/integration/channel.js

Issue: #1278 
Rollback PR #1272 
Solution: Remove `channel` stamp from the `universal` stamp and in the integration tests, use a direct instance of channel stamp replacing universal stamp instance `BaseAe`

Remove Channel stamp from Universal stamp

---

test/integration/channel.js

The following tests used to fail due to short polling.
- `can solo close a channel` 
-  `can dispute via slash tx`
Fix: both the tests use `sendTransaction` method with default poll blocks of height `+10`. Change it to 20 so that transaction confirmation will wait till 20 more blocks.

Fix Channel tests

---

docs/quick-start.md

Declares `height` variable used in `console.log('Current Block Height:', height)`

docs: quickstart height variable

---

src/utils/swagger.js

https://github.com/swagger-api/swagger-js/blob/e5788a8d1233b6cbbc0821d43392393c5a6ec607/src/http/index.js#L112-L114
- node may return 404 error with the empty body and without content-type when requesting `/v3/dry-run`
- swagger-client is unsure about content type and returns the response as Blob instead of string
- our check in `responseInterceptor` fails and sdk tries to parse Blob as JSON that makes unclear errors like:
```
{
name: 'SyntaxError',
message: "Unexpected 'o'",
at: 2,
text: '[object Blob]'
}
```
closes #1340

fix(swagger): detection of empty response

---

package-lock.json
package.json
src/utils/crypto.js
test/unit/crypto.js

- it was added in #466 without any reasoning
- it isn't used by sdk itself
- it is unclear who and for what reason can use it
- `nacl.box`/`nacl.box.open` can be used directly instead

refactor: remove unused asymmetric encode/decode functions

---

package.json

channel tests doesn't stop by themself without `exit` flag, I have accidentally removed it in https://github.com/aeternity/aepp-sdk-js/commit/bf15c1e07980c34b0197dd65b118ba39c3ee3fee#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L22-R22

test(integration): revert exit flag to speedup tests

---

src/utils/swagger.js
test/unit/swagger.js

depends on #1362 
closes #1082
closes #1028
```js
> const client = await genSwaggerClient('https://mainnet.aeternity.io/mdw/swagger/swagger.json')
> console.log(Object.keys(client.api))
[
'getBlockByHash',      'getBlockByKbi',
'getBlockByKbiAndMbi', 'getBlocks',
'getNameById',         'getAllNames',
'getActiveNames',      'getAllAuctions',
'getOwnedBy',          'getPointeesById',
'getPointersById',     'getOracle',
'getOracles',          'getActiveOracles',
'getInactiveOracles',  'getStatus',
'getTxByHash',         'getTxByIndex',
'getCurrentTxCount',   'getTxCountById',
'getTxsByDirection',   'getTxsByScopeTypeRange'
]
```

feat(swagger): converts operationId in snake case to pascal

---

babel.config.json
babel.esm.config.js
package-lock.json
package.json
src/contract/aci/index.js
src/tx/builder/helpers.js
src/utils/async-init.js
src/utils/keystore.js

depends on #1369 (needed for cli)
So, after this would be possible to do:
```js
import { Crypto } from '@aeternity/aepp-sdk/es/index.mjs'
console.log(Crypto.generateKeyPair())
```
and execute it using plain node:
```
$ node test.mjs
{
publicKey: 'ak_jnZsCzXTKdGDkdvSpExo46GwuWGv84CkzcvEtd6XdV98gLjd8',
secretKey: 'cb8556c8ff170c0075c3a8bdfa0343c83782e1ccbca0e7842a0caaee92c10fce61266723868d53aab664039e4088d72df242a1510f2bab2e9c67dbeb768ac1ad'
}
$ node --version                                            
v16.13.0
```

feat(package): build es version compatible with node

---

src/chain/node.js
src/node.js
src/utils/errors.ts
src/utils/swagger.js
test/integration/node.js

depends on #1362 
closes #1260

feat(poll): use getCheckTxInPool if available

---

test/integration/contract-aci.js

fix(contract events): don't throw error if events emitted by remote

---

.github/workflows/main.yml
package-lock.json
package.json
src/utils/keystore.js
test/unit/keystore.js
webpack.config.js

depends on https://github.com/antelle/argon2-browser/issues/66
before:
```
1.8M Feb  7 10:25 aepp-sdk.browser-script.js
838B Feb  7 10:19 aepp-sdk.browser-script.js.LICENSE.txt
5.8M Feb  7 10:25 aepp-sdk.browser-script.js.map
146K Feb  7 10:25 aepp-sdk.browser.js
581K Feb  7 10:25 aepp-sdk.browser.js.map
142K Feb  7 10:25 aepp-sdk.js
580K Feb  7 10:25 aepp-sdk.js.map
```
after:
```
723K Feb  7 10:46 aepp-sdk.browser-script.js
838B Feb  7 10:19 aepp-sdk.browser-script.js.LICENSE.txt
2.8M Feb  7 10:46 aepp-sdk.browser-script.js.map
146K Feb  7 10:49 aepp-sdk.browser.js
581K Feb  7 10:49 aepp-sdk.browser.js.map
142K Feb  7 10:49 aepp-sdk.js
580K Feb  7 10:49 aepp-sdk.js.map
```

perf: use argon2-browser instead of libsodium-wrappers-sumo

---

package.json

closes #1406 
https://github.com/babel/babel/issues/9803#issuecomment-505435797
I just ensured that it generates mjs files on windows, would be nice to check if it builds fine as a dependency.

fix(es): babel build on windows

---

babel.esm.config.js
package-lock.json
package.json
src/utils/aepp-wallet-communication/connection/browser-window-message.js
src/utils/aepp-wallet-communication/rpc/aepp-rpc.js
src/utils/aepp-wallet-communication/rpc/wallet-rpc.js
src/utils/keystore.js
test/environment/node.mjs

uuid fix details: https://github.com/uuidjs/uuid/pull/615

Improve compatibility with create-react-app

---

docs/guides/error-handling.md
package-lock.json
package.json
src/channel/handlers.js
src/index.js
src/tx/builder/helpers.js
src/utils/crypto.js
src/utils/errors.ts
src/utils/hd-wallet.js
src/utils/keystore.js
test/integration/channel.js
test/integration/oracle.js
test/integration/transaction.js
test/unit/crypto.js
test/unit/hd-wallet.js
test/unit/tx.js
webpack.config.js

I'm planning to rename `TxBuildHelper.decode/encode` to something more general, but it is not ready yet.
The need to switch from `bs58check` to `bs58` is explained in https://github.com/aeternity/aepp-calldata-js/pull/122.
[bip39](https://www.npmjs.com/package/bip39) package can be configured to support different languages and this is not up to SDK to decide which of them should be included. Also, it depends on a set of unnecessary crypto libraries that is not easy to get rid of: https://github.com/bitcoinjs/bip39/issues/170. It has a quite simple blockchain-agnostic interface. Our `@aeternity/bip39` didn't get updates in 3 years and probably shouldn't be used. So, I'm proposing to make the wallet developer use `bip39` package by himself and remove it from sdk.

Remove node stream polyfill

---

babel.esm.config.js
docs/compatibility.md
examples/browser/aepp/vue.config.js
examples/browser/wallet-iframe/vue.config.js
package-lock.json
package.json

closes #1364 
depends on https://github.com/aeternity/aepp-calldata-js/pull/114
depends on https://github.com/aeternity/aepp-calldata-js/pull/122
closes #1413 
found issues: https://github.com/dcposch/blakejs/pull/19 https://github.com/swagger-api/swagger-js/issues/2457

fix(babel): compatibility with create-react-app

---

.github/workflows/main.yml
docs/hooks.py
package.json

We are using "prepare" script to build sdk in case it is installed via git repo. It works fine except that "prepare" script are executed also at the end of "npm install". This behaviour is unwanted in some cases, it can be fixed by using "prepack" script instead (according the documentation).
https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts

chore(npm scripts): don't build on installing dependencies

---

src/utils/encoder.ts

before:
```
$ node test/environment/node.mjs
file:///.../aepp-sdk-js/es/utils/encoder.mjs:57
decode: string => getPayload(bs58.decode(string))
^
TypeError: bs58.decode is not a function
at decode (file:///.../aepp-sdk-js/es/utils/encoder.mjs:57:37)
at decode (file:///.../aepp-sdk-js/es/utils/encoder.mjs:83:19)
at Object.init (file:///.../aepp-sdk-js/es/account/memory.mjs:75:36)
at Stamp (/.../aepp-sdk-js/node_modules/@stamp/compose/index.js:34:41)
at file:///.../aepp-sdk-js/test/environment/node.mjs:13:16
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
after:
```
$ node test/environment/node.mjs
Height: 582859
Instanceof works correctly for nodes pool true
Contract deployed at ct_24BYktVcMedVCG6MnkeXvkAJbYYQZTNzbjKDg9LvbraFo8jSs8
Call result Map(2) { 'bar' => …
```

fix: importing in mjs

---

src/account/base.js
src/account/multiple.js
src/account/resolver.js
src/account/rpc.js
src/utils/aepp-wallet-communication/rpc/aepp-rpc.js
test/integration/accounts.js
test/integration/index.js
test/integration/rpc.js

closes #1390 
I'm proposing switch the default behaviour from transaction 
broadcasting by wallet to broadcasting by aepp and to remove the code for the first to simplify things.
I can't recall why broadcasting by wallet was introduced, but broadcasting by aepp is more natural from code perspective and also it would provide a better stack trase in case of failure.

feat(aepp): support external accounts in onAccount

---

.eslintrc.js

also I propose a fix to upstream: https://github.com/standard/eslint-config-standard-with-typescript/pull/802

chore: fix spacing around | in TypeScript

---

docs/guides/aens.md
docs/guides/build-wallet.md
docs/guides/error-handling.md
docs/quick-start.md
examples/browser/wallet-iframe/src/App.vue
examples/browser/wallet-web-extension/src/background.js
examples/browser/wallet-web-extension/src/content-script.js
examples/node/paying-for-tx-contract-call-tx.js
examples/node/paying-for-tx-spend-tx.js
src/ae/index.js
src/ae/oracle.js
src/index.js
src/tx/builder/helpers.js
src/tx/builder/index.js
src/tx/builder/schema.js
src/utils/amount-formatter.ts
src/utils/bytes.ts
src/utils/crypto.js
src/utils/keystore.js
test/integration/contract.js
test/integration/index.js
test/integration/paying-for.js
test/unit/keystore.js

Currently, to import something from `crypto` module you have to import it completely, like:
```js
import { Crypto } from '@aeternity/aepp-sdk-js';
Crypto.isAddressValid(...)
```
Tree shaking works better if imported only a specific thing, I'm proposing to make it possible by inlining `crypto` exports into `index` exports, making user import it by:
```js
import { isAddressValid } from '@aeternity/aepp-sdk-js';
isAddressValid(...)
```

index: Export in tree shaking friendly way

---

src/contract/aci.js
src/utils/errors.ts

closes #1315 
I think to expose just a transaction is enough, if necessary it can be transformed to transaction hash using `buildTxHash`
https://github.com/aeternity/aepp-sdk-js/blob/7b3d0e3b7f6d62c3099b9ffb3d5cca98ccec1dba/src/tx/builder/index.js#L451
or decoded using `unpackTx`
https://github.com/aeternity/aepp-sdk-js/blob/7b3d0e3b7f6d62c3099b9ffb3d5cca98ccec1dba/src/tx/builder/index.js#L433

feat(NodeInvocationError): store tx-encoded transaction

---

.eslintrc.js
.gitignore
docs/guides/contracts.md
package-lock.json
package.json
src/contract/aci.js
src/contract/compiler.js
src/utils/aepp-wallet-communication/rpc/aepp-rpc.js
test/index.js
test/integration/contract-aci.js
test/integration/contract.js
test/integration/index.js
tooling/autorest/compiler.yaml

fixes partially #1216 
found issues: https://github.com/aeternity/aesophia_http/issues/87 https://github.com/aeternity/aesophia_http/issues/88 https://github.com/aeternity/aesophia_http/issues/90 https://github.com/aeternity/aesophia_http/issues/91

Generate compiler api in TypeScript using autorest

---

src/typings/bip32-path/index.d.ts
src/typings/tweetnacl-auth/index.d.ts
src/utils/crypto.ts
src/utils/encoder.ts
src/utils/hd-wallet.ts
test/unit/hd-wallet.ts

closes #1475 
This PR migrates the `hd-wallet.js` util together with its corresponding test files to TS. It also adds types for the `bip32-path` and `tweetnacl-auth` modules

feat(utils): migrate hd-wallet.js to TS

---

src/account/base.js
src/account/rpc.js
src/node.js
src/utils/aepp-wallet-communication/rpc/aepp-rpc.js
src/utils/aepp-wallet-communication/rpc/rpc-client.js
src/utils/aepp-wallet-communication/rpc/wallet-rpc.js
src/utils/aepp-wallet-communication/schema.ts
test/integration/rpc.js

Originally Nikita asked is it possible to sign transaction for a different networks with no switching (passing `networkId`). We find out that the option is ignored in https://github.com/aeternity/aepp-sdk-js/blob/7a96386a1b9be8f4ca428f713b6a7e48f70b010f/src/utils/aepp-wallet-communication/rpc/aepp-rpc.js#L225 But it doesn't make sense to introduce this because of the check
https://github.com/aeternity/aepp-sdk-js/blob/dfbab5957dc3e7769427737f8f0b31fc1e63d20a/src/utils/aepp-wallet-communication/rpc/wallet-rpc.js#L134-L136
In general looks like it is enough to pass the `networkId` only from wallet to aepp. I can't find a reasonable case when we need to notify wallet about the network id that aepp uses.

refactor(wallet rpc)!: don't pass networkId from aepp to wallet

---

docs/guides/contracts.md

Just fixed some naming a bit, so there are no doubts which code we talking about.
I also have broader Idea in here. This page seems to me a bit more docs than practical example.
As a developer, I would like to see a straightforward working example. The guide here has a lot of aside explanation turnoffs and does not follow a straight line. So maybe it would deserve to create another section instead of wider explanation.
Let me know what you think.
The example I redone for myself ended up like this.
```
const CONTRACT_SOURCE_CODE =
`
contract Increment =
record state =
{ count: int }
entrypoint init(start: int) =
{ count = start }
stateful entrypoint increment(value: int) =
put(state{ count = state.count + value })
entrypoint get_count() =
state.count
`
const contractInstance = await …
```

docs: update instructions of contract guide

---

docs/guides/error-handling.md
src/utils/errors.ts
src/utils/hd-wallet.ts
test/unit/hd-wallet.ts

I'm sure that `NotHardenedSegmentError` and `UnsupportedChildIndexError` should be combined because they actually refers to the same issue. But do we need to be able to distinglish between invalid derivation path root and not hardened segment in the path on the level of classes? We already have a lot of error classes, I don't think that we need 3 of them for derivation.

Combine derivation errors to a single class, add Bip32Path type

---

examples/browser/aepp/src/Basic.vue
src/ae/index.js
src/channel/index.js
src/utils/errors.ts
test/integration/accounts.js

related issues: https://github.com/aeternity/aeternity/issues/3645 https://github.com/aeternity/protocol/issues/489

refactor: rename tokens to coins

---

.github/workflows/main.yml
docs/hooks.py
package.json

well, the last change didn't work, this is still an issue, the only fix we have is `--ignore-scripts`, https://github.com/npm/rfcs/discussions/261 https://stackoverflow.com/questions/44499912/why-is-npm-running-prepare-script-after-npm-install-and-how-can-i-stop-it
reverts #1454 
This reverts commit 2099ea5b33571aa3761b24e444b87feb57936b47.

Revert "chore(npm scripts): don't build on installing dependencies"

---

src/utils/crypto.ts
src/utils/encoder.ts

generateKeyPair: return different type depending on raw value

---

src/account/rpc.ts
tsdoc.json

networkId is marked deprecated but using now to make SDK v12 aepps compatible with wallets using v11.0.1 and below.
Closes #1559

fix(aepp): use networkId in rpc tx signing

---

src/AeSdkWallet.ts
src/utils/aepp-wallet-communication/rpc/types.ts

Closes #1561
It's a bit misleading and hard to fix since the earlier releases shipped with schema which returns tx blob in `transactionHash` key. 
This is the fix to make aepps using SDK v11 and below compatible with wallets using SDK v12.

fix(wallet): revert to returning complete tx data instead of just hash in rpc wallet signing

---

src/chain.ts
src/oracle.ts
src/utils/errors.ts

`awaitHeight` was accepting the amount of attempts by default equal to 20 that actually should
depend on a difference between current and desired heights. Usually we assume that used node is
being synced therefore any height should be reachable. We are not doing a real-time operating
system, so we don't care about riching a height in a limited time.
Docs related to a similar change in oracles: https://github.com/aeternity/protocol/blob/71cf111ac6b5cc5830999bd130fa0bd753504195/oracles/oracle_transactions.md

fix(awaitHeight): allow to wait for arbitrary number of blocks

---

webpack.config.js

`dist/aepp-sdk.js` still used in some cases. It is intended for non-browser usage, so package size is not a priority. Disabling minification would simplify debugging. For example, developer may add some debug printing on sdk side. If unhandled exception thrown by sdk, node print the line, it is much more readable with disabled minification.

chore: don't minimize node build

---

commitlint.config.js

based on scopes used in the latest release: https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/CHANGELOG.md#1200-2022-06-17

chore: limit scopes that can be used in commit messages

---

src/typings/blakejs/index.d.ts
src/typings/sha-js/index.d.ts
src/utils/crypto.ts
src/utils/encoder.ts
src/utils/hd-wallet.ts

Initial idea was to get rid of `aes-js`, but the best would be to drop `encryptKey`, `decryptKey` functions firstly.

Import specific versions of blakejs and sha.js

---

src/utils/crypto.ts

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
`MAX_SAFE_INTEGER` is 2^53 – 1, so it is 53 bits long. 64 bits enough to generate a value between 0 and this `MAX_SAFE_INTEGER`.

fix: use crypto random to generate salt

---

src/AeSdkBase.ts
src/AeSdkWallet.ts
src/account/Base.ts
src/account/Rpc.ts
test/unit/memory-account.ts

BREAKING CHANGE: `signMessage` always return `Uint8Array`
Use `Buffer.from(signature).toString('hex')` to convert it to hex.
closes #1485

refactor!: remove returnHex option in signMessage

---

src/AeSdk.ts

BREAKING CHANGE: `removeAccount` throws error if account not found
This is made to prevent unintended behaviour and to enable "no-console" rule in future.

refactor!: throw error if account not found in `removeAccount`

---

src/AeSdkBase.ts
src/account/Base.ts
src/tx/validator.ts
src/utils/crypto.ts
test/integration/rpc.ts
test/unit/crypto.ts
test/unit/memory-account.ts

BREAKING CHANGE: `verifyMessage` removed from accounts and AeSdkBase
Use `verifyMessage` exported in root instead.
BREAKING CHANGE: `verify` and `verifyMessage` accepts address instead of hex string or Uint8Array
Convert public key in Uint8Array to address using `encode(pk, 'ak')`.
Convert public key in hex to address using `encode(Buffer.from(pk, 'hex'), 'ak')`.

refactor!: remove `verifyMessage` from accounts and AeSdkBase

---

src/AeSdkWallet.ts
src/Node.ts

BREAKING CHANGE: `url` property of `Node` removed
Use autorest's `$host` property instead.

refactor(node)!: drop duplicate `url` property

---

package.json

BREAKING CHANGE: Subpaths imports of SDK are not allowed
SDK does versioning only for the API provided in the root export.
Replace subpaths imports with imports of the package root.
```diff
-import MemoryAccount from '@aeternity/aepp-sdk/es/account/Memory.mjs';
+import { MemoryAccount } from '@aeternity/aepp-sdk';
```
closes #1133

chore!: add `exports` field to package.json

---

docs/index.md
test/environment/browser.html
webpack.config.js

closes #1114
BREAKING CHANGE!: umd export renamed from `Ae` to `Aeternity`
Use `window.Aeternity` instead of `window.Ae` in browser.

refactor!: rename umd export to `Aeternity`

---

src/AeSdk.ts
src/AeSdkAepp.ts
src/AeSdkBase.ts
src/AeSdkMethods.ts
src/AeSdkWallet.ts
src/index.ts

related discussion: https://github.com/aeternity/aepp-sdk-js/issues/456
AeSdkMethods doesn't have 1 to 1 relation (can change `_options` and override them in the last argument), but also doesn't provides extra API.
Also, extraction of AeSdkMethods improves readability.

feat: extract AeSdkMethods class with minimal interface

---

src/contract/Contract.ts
src/utils/errors.ts
test/integration/contract-aci.ts

fix(contract): don't throw ambiguous error if event types the same

---

babel.config.js

based on https://github.com/subhod-i/aepp-sdk-js/commit/a7d816822c045cedbecb4204e38bc06d4b109986
I don't think that SDK needs `@babel/plugin-proposal-private-property-in-object` plugin because it doesn't uses `#property in object` (https://babeljs.io/docs/en/babel-plugin-proposal-private-property-in-object)

fix: compatibility with @vue/cli@4

---

.github/workflows/main.yml
.gitignore
.mocharc.js
babel.config.js
babel.esm.config.js
package-lock.json
package.json
src/AeSdkBase.ts
src/AeSdkMethods.ts
src/Node.ts
src/account/Base.ts
src/contract/Contract.ts
src/contract/compiler/Base.ts
src/contract/compiler/Cli.ts
src/contract/compiler/Http.ts
src/contract/compiler/getFileSystem.ts
src/contract/ga.ts
src/index.ts
test/integration/compiler.ts
test/integration/contract-aci.ts
test/integration/contracts/Includes.aes
test/integration/contracts/Increment.aes
test/integration/contracts/lib/Library.aes
test/integration/contracts/lib/Sublibrary.aes
test/integration/ga.ts
test/integration/rpc.ts
tooling/babel-register.js
tooling/fetch-aesophia-cli.mjs
tsconfig.json
webpack.config.js

closes #1693 
found issues https://github.com/aeternity/aesophia_cli/issues/71 https://github.com/aeternity/aesophia_cli/issues/72 https://github.com/aeternity/aesophia_cli/issues/73 https://github.com/aeternity/aesophia_cli/issues/74 https://github.com/aeternity/aesophia_cli/issues/75

Add CompilerCli

---

src/channel/Base.ts
src/channel/Contract.ts
src/channel/internal.ts
test/integration/channel.ts

closes #1619 
This PR adds a stateless support for created contracts on channel.
Peers can listen on `onNewContract` events and also access created contract addresses through `channel.contracts()`.
Due to the fact that the node API does not provide way to fetch deployed contract addresses, the implementation is stateless which means that for example in (browser) cases, where users refresh their window and reconnects, they will lose access to given array of contract addresses. Given this, `channel.contracts()` might be a good discussion point whether if it should be kept or removed

feat(channel): add helper to get contract address created by other peer

---

src/channel/Base.ts
src/channel/handlers.ts
src/channel/internal.ts

closes #1710 
Fixes snake formats to camelCase for some unhandled events such as `peerDisconnected`
Provides strongly typed events, see screenshots of use cases:

refactor(channel): strongly type events

---

src/Node.ts
src/utils/autorest.ts
test/integration/node.ts

closes #1630 
found issues https://github.com/aeternity/aeternity/pull/4084
Attempt | Intermediate | Delay
-- | -- | --
0 | 0 | 0
1 | 0.33 | 55.55
2 | 0.66 | 222.22
3 | 1 | 500
  | Delay sum | 777.77
This is a bit different than Dincho suggested, I would reduce the amount of retries and make it truly exponential 🙂

feat(node): exponential retry of requests on failure

---

src/channel/Base.ts
src/channel/handlers.ts
src/channel/internal.ts
test/integration/channel.ts

BREAKING CHANGE: Channel:state returns unpacked entries Use `buildTx` to pack them back if needed.

refactor(channel)!: return unpacked entries in `state` method

---

docs/guides/oracles.md
src/oracle.ts
test/integration/oracle.ts

BREAKING CHANGE: `onQuery` callback of `pollForQueries`, `oracle.pollQueries` accepts a single query
It was accepting an array before. Apply a patch:
```diff
-aeSdk.pollForQueries(oracleId, (queries) => queries.forEach(handleQuery));
+aeSdk.pollForQueries(oracleId, handleQuery);
```
closes #1383 

refactor(oracle): pass queries one by one in pollForQueries

---

src/aepp-wallet-communication/rpc/types.ts

To ensure that no breaking changes in protocol.

refactor(wallet,aepp): inline sendTransaction return type

---

src/tx/builder/field-types/nonce.ts
src/tx/validator.ts
test/environment/name-claim-unmined.mjs
test/examples.sh
test/integration/txVerification.ts

Sometime before we implemented support for `getAccountNextNonce` node's endpoint, this endpoint had a `strategy` option that may result in a different nonce. While so, the generated nonce is still validated the old way, to validate it correctly, the transaction validator should know the chosen strategy. Instead of complicating validator API, I would integrate it into the transaction builder https://github.com/aeternity/aepp-sdk-js/issues/1763. Let's omit the nonce validation until it is implemented.

fix(tx-builder): drop nonce validator to avoid false positive

---

src/chain.ts

Currently if transaction can't be mined but present in mempool, sdk by default would wait for 10 blocks before sdk would fail. Considering it takes 3 minutes to mine a generation, this would fail after 30 minutes, that is extremely long time to wait. I propose to reduce this 2 times (to 15 minutes). Thought it can be even smaller, 2 blocks?

fix(chain): reduce /2 number of blocks to wait before throwing timeout

---

package.json
test/integration/compiler.ts
tooling/generate-schema.ts

```
> @aeternity/aepp-sdk@13.0.0-beta.0 build:generate
> tooling/generate-schema.ts
'tooling' is not recognized as an internal or external command,
operable program or batch file.
```

chore: build and test compatibility with Windows

---

docs/README.md
test/integration/accounts.ts

docs: warn about incompatibility with `strictFunctionTypes`

---

src/aepp-wallet-communication/wallet-detector.ts

This happened for historical reasons, before the `wallets` object was the same for multiple calls of `walletDetector`.

fix(aepp): don't call `onDetected` with empty wallet array

---

.github/workflows/docs-develop.yml
.github/workflows/docs-release.yml
.github/workflows/main.yml
docs/conda.yml

Fixes warning
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2, actions/cache@v2

ci: update GH actions and conda.yml

---

package.json
src/Node.ts

Fixes compatibility with @vue/tsconfig
https://github.com/vuejs/tsconfig#migrating-from-typescript--50
https://nodejs.org/api/packages.html#community-conditions-definitions

provide types in exports field of package.json

---

docs/guides/error-handling.md
src/AeSdkWallet.ts
src/aepp-wallet-communication/rpc/RpcClient.ts
src/aepp-wallet-communication/schema.ts
src/deprecated.ts
src/index-browser.ts

The idea is that we need a strict set of defined errors between aepp and wallet, other errors should be communicated as internal errors and be handled on the emitter side.
related to #1826 

Don't expose internal errors in broadcast, throw reason of internal errors on wallet side

---

package.json

based on https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#exports-is-prioritized-over-typesversions

chore: specify fallback types in `exports` of package.json

---

src/contract/Contract.ts
test/integration/Middleware.ts
test/integration/contract-aci.ts

closes https://github.com/aeternity/aepp-sdk-js/issues/1844

fix(contract): use fallback account if `onAccount` not provided

---

test/integration/Middleware.ts
tooling/autorest/middleware-prepare.mjs
tooling/autorest/middleware.yaml

found issues: https://github.com/aeternity/ae_mdw/issues/1421 https://github.com/aeternity/ae_mdw/pull/1422 https://github.com/aeternity/ae_mdw/pull/1426 https://github.com/aeternity/ae_mdw/pull/1424 https://github.com/aeternity/ae_mdw/pull/1427
related issues: https://github.com/Azure/autorest.typescript/issues/1175#issuecomment-1434657324 https://github.com/Azure/autorest/issues/4118

chore(middleware): update swagger file to the latest version

---

docker-compose.yml
src/contract/compiler/Base.ts
src/contract/compiler/Cli.ts
src/contract/compiler/Http.ts
src/contract/compiler/HttpNode.ts
test/integration/Middleware.ts
test/integration/compiler.ts
test/integration/contract-aci.ts
test/integration/contracts/Includes.json
test/integration/contracts/Increment.aes
test/integration/contracts/Interface.aes
test/integration/contracts/lib/DecrementInterface.aes
test/integration/transaction.ts
tooling/autorest/compiler-prepare.mjs
tooling/autorest/middleware-prepare.mjs
tooling/fetch-aesophia-cli.mjs
tsconfig.tests.json

closes https://github.com/aeternity/aepp-sdk-js/issues/1845
blocked by:
- release of aesophia_cli
- https://github.com/aeternity/aesophia_http/pull/121

feat(compiler): add `generateAci`, `generateAciBySourceCode`

---

examples/browser/aepp/src/App.vue
examples/browser/aepp/src/DelegationSignature.vue
examples/browser/wallet-iframe/src/App.vue
examples/browser/wallet-web-extension/src/background.js
src/AeSdkBase.ts
src/AeSdkWallet.ts
src/account/Base.ts
src/account/Generalized.ts
src/account/Ledger.ts
src/account/Memory.ts
src/account/Rpc.ts
src/aepp-wallet-communication/rpc/types.ts
src/aepp-wallet-communication/schema.ts
src/contract/delegation-signature.ts
test/integration/contract.ts
test/integration/rpc.ts

closes #1758
Test UI added to aepp example
The last time I try to move `createDelegationSignature` to Contract, now I'm moving it to AccountBase 🙃 This is need to be in accordance with the current aepp-wallet permission model.

Delegation signature over aepp-wallet connection

---

examples/browser/aepp/src/App.vue
examples/browser/aepp/src/Connect.vue
examples/browser/aepp/src/store.js
examples/browser/aepp/src/styles.scss
examples/browser/wallet-iframe/src/App.vue
examples/browser/wallet-iframe/src/styles.scss
examples/browser/wallet-web-extension/src/styles.scss
src/AeSdkWallet.ts
test/integration/rpc.ts

Aepp-wallet connection fixes

---

docs/CHANGELOG.md
package-lock.json
package.json
src/contract/Contract.ts
src/tx/builder/field-types/u-int.ts
test/integration/contract-aci.ts

* use `Number` instead of unary plus for BigInt ([33fcfb4](https://github.com/aeternity/aepp-sdk-js/commit/33fcfb452b7340b73a13300e19cfeb83a94406c2))

Release 13.2.1

---

docker-compose.yml
docker/aeternity_node_mean16.yaml
src/tx/builder/constants.ts
src/tx/builder/field-types/ct-version.ts

feat: use proper vm version in Ceres

---

src/aepp-wallet-communication/rpc/types.ts
src/aepp-wallet-communication/wallet-detector.ts

fix(aepp): use complete type of WalletInfo object

---

src/utils/autorest.ts

In general node shouldn't return 500 code. And I don't know cases when it should be retried.
Also, it looks like our API gateway has a kind of protection of doing frequent requests that fail with 500 code: there is an exponentially growing delay in receiving a response.
For example, I was retrying https://testnet.aeternity.io/v3/dry-run
requested at 2023-08-27T16:23:08.129Z 
responded at 2023-08-27T16:23:13.594Z with 500 code in 5 seconds
requested at 2023-08-27T16:23:13.652Z
responded at 2023-08-27T16:23:28.214Z with 500 code in 15 seconds
requested at 2023-08-27T16:23:28.444Z
responded at 2023-08-27T16:24:16.582Z with 500 code in 48 seconds
requested at 2023-08-27T16:24:17.096Z
responded at 2023-08-27T16:26:04.847Z with 500 code in 107 seconds
So, in this case, request retrying making …

fix(node): don't retry 500 code responses

---

src/utils/autorest.ts

I was making a lot of transactions one by one and because of the occasionally wrong nonce, some tx was rejected. The whole process was crushing since these exceptions weren't possible to handle.

fix(node): uncatchable exception if request failed in queue

---

src/contract/Contract.ts

To avoid DuplicateContractError if signing was rejected or so.

fix(contract): don't mark contract as deployed if tx failed

---

examples/browser/wallet-web-extension/src/content-script.js
examples/browser/wallet-web-extension/src/manifest.json
src/aepp-wallet-communication/wallet-detector.ts
test/environment/browser-aepp.html

fix(aepp,wallet): connect to web-extension if opened over file:///

---

examples/browser/aepp/src/Connect.vue
examples/browser/wallet-iframe/src/App.vue
examples/browser/wallet-iframe/src/styles.scss

Add url input and "show aepp" button to wallet-iframe example

---

src/Node.ts
test/integration/node.ts

fix(node): throw clear error message if unsupported protocol

---

docs/guides/address-length.md
docs/guides/contracts.md
docs/guides/paying-for-tx.md
examples/node/transfer-ae.mjs
src/Middleware.ts
src/Node.ts
src/contract/compiler/Cli.ts

docs(compiler): explain `compilerPath` argument and related fixes

---

.github/workflows/main.yml
docker-compose.yml
test/integration/Middleware.ts

ci: use `docker-compose --wait` instead of custom script

---

src/tx/validator.ts
test/integration/txVerification.ts

based on https://github.com/aeternity/aeternity/pull/4237

feat(tx-builder): reject used accounts in GaAttachTx in Ceres

---

docs/guides/error-handling.md
src/tx/builder/common.ts
src/tx/builder/field-types/index.ts
src/utils/crypto.ts
test/unit/crypto.ts

Multiple encodings in `isAddressValid`, simplify exports in tx builder, correct schema picking

---

package-lock.json
package.json
test/integration/contract-aci.ts

depends on https://github.com/aeternity/aepp-calldata-js/pull/258

test(contract): ensure bytes any size works

---

docker-compose.yml
docs/guides/aens.md
package-lock.json
package.json
src/aens.ts
src/tx/builder/field-types/index.ts
src/tx/builder/field-types/pointers2.ts
src/tx/builder/schema.ts
test/integration/aens.ts
test/integration/contract-aci.ts
test/integration/delegation.ts
test/integration/transaction.ts
tooling/fetch-aesophia-cli-8.mjs

based on https://github.com/aeternity/aeternity/pull/4056
found issues https://github.com/aeternity/protocol/issues/521

Support Ceres raw pointers in NameUpdate and delegation signatures

---

src/contract/compiler/Base.ts
src/contract/compiler/Cli.ts
src/contract/compiler/Http.ts
src/contract/compiler/HttpNode.ts
test/integration/compiler.ts
tooling/autorest/compiler-prepare.mjs

closes #1876
depends on https://github.com/aeternity/aesophia_http/pull/128

Provide compilation warnings

---

examples/browser/aepp/src/store.js
src/account/Memory.ts

MemoryAccount types, fix example aepp

---

src/aens.ts
src/chain.ts
src/contract/Contract.ts
src/contract/ga.ts
src/oracle.ts
src/spend.ts
src/tx/builder/field-types/nonce.ts
src/tx/builder/field-types/ttl.ts
test/integration/aens.ts
test/integration/chain.ts
test/integration/contract-aci.ts
test/integration/paying-for.ts
test/integration/~execution-cost.ts

How sdk would work after this PR:
- transactions built using `buildTx`, `AeSdk:buildTx`, `buildTxAsync` will have ttl set to 0 (as before)
- transactions built while executing sdk's methods (like `aeSdk.spend(...)`) would have ttl set to `~height + 3`, with the ability to override this value though global and method's options `{ ttl: 0 }`
- poll of transaction with ttl set to 0 by default will wait for 5 blocks before rejecting (as before)
- poll of transaction with ttl set to not 0 will wait till transaction would be removed from mempool (the same as `ttl` expires)
Doing this way sdk would ensure that the transaction won't get stuck in mempool, so it won't affect next-nonce calculation. Also, this transaction won't get mined after polling …

Set ttl to height + 3 for transactions built internally

---

docker-compose.yml
docs/guides/batch-requests.md
docs/transaction-options.md
src/AeSdkMethods.ts
src/Node.ts
src/chain.ts
src/tx/builder/constants.ts
src/tx/builder/field-types/fee.ts
src/tx/builder/field-types/gas-limit.ts
src/tx/builder/field-types/gas-price.ts
src/tx/builder/index.ts
test/dynamic-gas-price.html
test/integration/chain.ts
test/integration/node.ts
test/integration/transaction.ts
tooling/autorest/node.yaml

closes https://github.com/aeternity/aepp-sdk-js/issues/1786
To protect from funds loss in case of a bug/misusage, I propose to add an upper limit for the gas price substituted by default. Known issues:
If somebody posts transactions from a single client with high blockchain utilization, the gas price will increase for no reason. This is a special use case, I'm adding a note to `batch-requests.md`.
With a low utilization, it is expected to get a transaction mined within 3 seconds. Currently, it is cheap to increase utilization at any moment. The current solution would reflect utilization change in a minute. So, a user may experience arbitrary changes of mining time.
I've wrote a script to create several clients pushing transactions one by one …

feat(tx-builder): get actual gas price from node

---

docker-compose.yml

related https://github.com/aeternity/aeternity/pull/4292 https://github.com/aeternity/aesophia_http/pull/133

ci: set `healthcheck.interval` to run containers faster

---

docker/aeternity.yaml
examples/browser/aepp/src/Basic.vue
examples/browser/aepp/src/components/DataSign.vue
examples/browser/wallet-iframe/src/App.vue
examples/browser/wallet-web-extension/src/background.js
src/AeSdkWallet.ts
src/account/Base.ts
src/account/Rpc.ts
src/aepp-wallet-communication/rpc/types.ts
src/aepp-wallet-communication/schema.ts
test/integration/chain.ts
test/integration/node.ts
test/integration/rpc.ts
test/unit/ledger.ts

The ability to sign raw data implemented as a fallback in case the payload that aepp needs to sign is not compatible with existing methods.
Wallet needs to warn user if it can't parse the data to sign. Or wallet can disable this method, to work only with a known payloads.

feat(aepp,wallet): allow raw data sign

---

docs/guides/jwt.md
examples/browser/aepp/src/App.vue
examples/browser/aepp/src/Jwt.vue
mkdocs.yml
src/index-browser.ts
src/utils/jwt.ts
test/unit/jwt.ts

feat: jwt utilities

---

src/AeSdkAepp.ts
test/integration/rpc.ts

Because it is not checked/required on the other side.

fix(aepp): don't require subscription to request addresses

---

docs/guides/contracts.md
examples/browser/aepp/src/Contracts.vue
examples/node/contract-interaction.mjs
examples/node/paying-for-contract-call-tx.mjs
src/AeSdkMethods.ts
src/contract/Contract.ts
test/environment/browser-aepp.html
test/environment/browser.html
test/environment/ledger/main.mjs
test/environment/node.js
test/environment/node.mjs
test/environment/node.ts
test/integration/AeSdkMethods.ts
test/integration/account-generalized.ts
test/integration/aens.ts
test/integration/chain.ts
test/integration/channel.ts
test/integration/contract-aci.ts
test/integration/contract.ts
test/integration/delegation.ts
test/integration/paying-for.ts
test/integration/rpc.ts
test/integration/transaction.ts
test/integration/typed-data.ts

AeSdk:initializeContract makes AeSdk to depend on Contract, and to depend on @aeternity/aepp-calldata eventually.
closes partially https://github.com/aeternity/aepp-sdk-js/issues/1839

Remove AeSdk:initializeContract

---

.mocharc.js
test/integration/aens.ts
test/integration/chain.ts
test/integration/channel-contracts.ts
test/integration/channel-other.ts
test/integration/channel-utils.ts
test/integration/channel.ts
test/integration/contract.ts
test/integration/delegation.ts
test/integration/index.ts
test/integration/oracle.ts
test/integration/typed-data.ts

closes https://github.com/aeternity/aepp-sdk-js/issues/1923
blocked by https://github.com/aeternity/aeternity/issues/4234

test: run state channel tests on testnet

---

src/tx/builder/helpers.ts
test/unit/aens.ts

https://github.com/aeternity/protocol/blob/d634e7a3f3110657900759b183d0734e61e5803a/AENS.md#name
https://www.unicode.org/reports/tr46/#Validity_Criteria
https://testnet.aeternity.io/v3/names/-test.chain
https://testnet.aeternity.io/v3/names/test-.chain
https://testnet.aeternity.io/v3/names/te--st.chain

fix(aens): validate minus chars in name as aenode does

---

docker-compose.yml

ci: update aenode to 7.2.0

---

src/utils/autorest.ts
test/integration/Middleware.ts
test/integration/node.ts
tooling/autorest/middleware.yaml
tooling/autorest/node.yaml

found issues https://github.com/aeternity/ae_mdw/issues/1891 https://github.com/aeternity/ae_mdw/issues/1901 https://github.com/aeternity/aeternity/issues/4386

Return time as Date instance

---

docs/README.md

closes #2012
found issues https://github.com/aeternity/aescan/issues/899 https://github.com/aeternity/aescan/issues/900 https://github.com/aeternity/aescan/issues/901 https://github.com/aeternity/aescan/issues/902 https://github.com/aeternity/aescan/issues/903 https://github.com/aeternity/aescan/issues/904 https://github.com/aeternity/aescan/issues/905

docs: don't suggest `shallowReactive` since it is not working

---

src/tx/execution-cost.ts
test/integration/~execution-cost.ts

closes #2016 
Anyway the amount needs to be on balance to mine such transaction.

fix(tx-builder): count amount in execution cost when spend to yourself

---

src/aens.ts
test/integration/aens.ts
tooling/autorest/node.yaml
tooling/autorest/postprocessing.js

found issues https://github.com/aeternity/aeternity/pull/4537

AENS fixes and improvements

---

src/contract/Contract.ts
src/utils/errors.ts
test/integration/contract-aci.ts

feat: show function name along its hash if missed in bytecode

---

src/account/MnemonicFactory.ts
src/aepp-wallet-communication/connection/BrowserRuntime.ts
test/unit/mnemonic.ts

needed for https://github.com/superhero-com/superhero-wallet/pull/3444

AccountMnemonicFactory: init by seed and sync methods

---

docs/guides/low-vs-high-usage.md
examples/node/_api-high-level.js
examples/node/_api-low-level.js
package.json
test/examples.sh

Update low/high level api docs

---

examples/browser/aepp/src/components/ConnectFrame.vue
examples/browser/aepp/src/components/ConnectLedger.vue
examples/browser/aepp/src/components/SelectNetwork.vue
examples/browser/wallet-iframe/src/App.vue

Example aepp fixes

---

examples/browser/aepp/package.json
examples/browser/aepp/src/components/ConnectLedger.vue

https://www.npmjs.com/package/@ledgerhq/hw-transport-web-ble
temporary test at https://davidyuk.github.io/aepp-sdk-js/develop/examples/browser/aepp/
the exception that can't be handled https://github.com/LedgerHQ/ledger-live/issues/6746
ble support in browsers https://caniuse.com/web-bluetooth
added a workaround to connect via ble on android https://github.com/LedgerHQ/ledgerjs/issues/352
It works on desktop/Android Chrome via USB and BLE transports. Not working in Safari at all.

docs(account): connect to Ledger over Bluetooth in example aepp

---

src/channel/Contract.ts
src/tx/builder/field-types/nonce.ts
test/integration/Middleware.ts
tooling/autorest/middleware.yaml
tooling/autorest/node.yaml

found issues https://github.com/aeternity/ae_mdw/issues/2136 https://github.com/aeternity/ae_mdw/issues/2137
https://azure.github.io/autorest/extensions/#x-ms-enum

fix(node,middleware): more strict enum handling

---

package.json
tooling/autorest/compiler.yaml
tooling/autorest/middleware.yaml
tooling/autorest/node.yaml
tooling/autorest/postprocessing.js
tooling/docs/examples-to-md.js

In Ubuntu:
```
sh -c "echo [^b]*"
```
does the same as
```
sh -c "echo b*"
```

docs: fix example generation by doing files match in js
